// ===========================
// UK Auction Houses Hub - Data
// Compiled from publicly available sources. Verify independently before making investment decisions.
// ===========================

const AUCTION_HOUSES = [
  {
    id:1, name:"Acuitus", url:"https://www.acuitus.co.uk/",
    desc:"Leading UK commercial property auctioneer specialising in investment-grade retail, office, leisure and mixed-use assets. One of the most established names in commercial auction sales nationally.",
    spec:"Commercial", lots:["Commercial Investment","Retail","Office","Leisure","Mixed Use"],
    conditions:["Modern","Refurbishment"], tenure:"Mixed",
    niches:["Commercial Investment","Leisure & Hotels","Retail Parks"],
    reach:"National", regions:["London","South East","National"], area:"London & Nationwide",
    successRate:78, premium:"Moderate", bargains:"Low",
    vendors:["Corporate","Institutional","Private"], vendorPrimary:"Corporate & Institutional",
    format:"Hybrid", buyerPrem:"2% + VAT", deposit:"10%", completion:20,
    dataRating:5, historical:true, catalogue:true,
    highlights:["Market-leading commercial auctioneer","Excellent historical result data and catalogues","Regular high-value national auction events","Strong institutional vendor base"]
  },
  {
    id:2, name:"Agents Property Auction", url:"https://www.agentspropertyauction.com/",
    desc:"Online property auction platform working with local estate agents across England and Wales. Offers modern method of auction for residential properties through partner agents.",
    spec:"Residential", lots:["Residential Houses","Residential Flats","Buy-to-Let"],
    conditions:["Modern","Refurbishment"], tenure:"Mostly Vacant",
    niches:["Residential Resale"],
    reach:"National", regions:["National","Midlands","North West","South East"], area:"England & Wales via agent network",
    successRate:72, premium:"Moderate", bargains:"Moderate",
    vendors:["Private","Probate"], vendorPrimary:"Private Vendors",
    format:"Online", buyerPrem:"Varies by agent", deposit:"10%", completion:28,
    dataRating:3, historical:false, catalogue:true,
    highlights:["Modern method of auction platform","Works through network of local estate agents","Good geographic coverage through partner network"]
  },
  {
    id:3, name:"Aldreds", url:"https://www.aldreds.co.uk/",
    desc:"Established Norfolk-based estate agents and auctioneers covering Great Yarmouth, Gorleston and surrounding areas. Regular auction sales of residential and some commercial properties.",
    spec:"Residential", lots:["Residential Houses","Residential Flats","Commercial"],
    conditions:["Refurbishment","Modern"], tenure:"Mostly Vacant",
    niches:["Coastal Properties","Holiday Lets"],
    reach:"Regional", regions:["East Anglia","Norfolk"], area:"Great Yarmouth & Norfolk",
    successRate:70, premium:"Low", bargains:"Moderate",
    vendors:["Private","Probate","Lender"], vendorPrimary:"Private & Probate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:2, historical:false, catalogue:true,
    highlights:["Strong local presence in Great Yarmouth area","Good for coastal and holiday let opportunities","Established regional auctioneer"]
  },
  {
    id:4, name:"All Wales Auction", url:"https://www.allwalesauction.co.uk/",
    desc:"Dedicated Welsh property auctioneer offering residential and land lots across all regions of Wales. Provides both room and online bidding options for Welsh property.",
    spec:"Residential", lots:["Residential Houses","Land","Development Sites","Rural"],
    conditions:["Refurbishment","Development","Modern"], tenure:"Mostly Vacant",
    niches:["Welsh Property","Rural Land","Development Opportunities"],
    reach:"Regional", regions:["Wales","South Wales","North Wales","Mid Wales"], area:"All Wales",
    successRate:72, premium:"Low", bargains:"Moderate",
    vendors:["Private","Probate","Lender"], vendorPrimary:"Private & Probate",
    format:"Hybrid", buyerPrem:"2% + VAT", deposit:"10%", completion:28,
    dataRating:3, historical:false, catalogue:true,
    highlights:["Covers all regions of Wales comprehensively","Good selection of development sites and land","Both room and online bidding available"]
  },
  {
    id:5, name:"Allsop", url:"https://www.allsop.co.uk/auctions/",
    desc:"One of the UK's largest and most prestigious property auctioneers. Major force in both commercial and residential auction markets with excellent data transparency and regular high-volume national sales.",
    spec:"Mixed", lots:["Commercial Investment","Residential","Development Sites","Ground Rents","Mixed Use"],
    conditions:["Modern","Refurbishment","Development"], tenure:"Mixed",
    niches:["Ground Rents","Commercial Investment","Residential Investment","Development Land"],
    reach:"National", regions:["London","National","South East","Midlands"], area:"London & Nationwide",
    successRate:80, premium:"Moderate", bargains:"Low",
    vendors:["Corporate","Lender","Institutional","Private"], vendorPrimary:"Corporate, Lender & Institutional",
    format:"Hybrid", buyerPrem:"2% + VAT", deposit:"10%", completion:20,
    dataRating:5, historical:true, catalogue:true,
    highlights:["One of the UK's largest property auctioneers","Excellent historical data and downloadable catalogues","Strong commercial and residential sales","Major lender and institutional vendor base","Regular high-volume auction events"]
  },
  {
    id:6, name:"Andrew Craig", url:"https://www.andrew-craig.co.uk/",
    desc:"North East England estate agents based in Gateshead and Low Fell. Conduct periodic property auctions featuring residential properties in the Tyneside and wider North East area.",
    spec:"Residential", lots:["Residential Houses","Residential Flats","Buy-to-Let"],
    conditions:["Refurbishment","Modern"], tenure:"Mixed",
    niches:["North East Buy-to-Let","Terraced Housing"],
    reach:"Regional", regions:["North East","Tyneside"], area:"Gateshead & Tyneside",
    successRate:68, premium:"Low", bargains:"Moderate",
    vendors:["Private","Probate"], vendorPrimary:"Private & Probate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:2, historical:false, catalogue:false,
    highlights:["Strong local knowledge of Tyneside market","Good buy-to-let opportunities in North East","Competitive guide prices for residential lots"]
  },
  {
    id:7, name:"Andrew Grant", url:"https://www.andrewgrant.co.uk/",
    desc:"Worcestershire-based chartered surveyors and property consultants. Conduct regular auctions of residential, commercial and rural properties across the West Midlands and Welsh Borders.",
    spec:"Mixed", lots:["Residential Houses","Commercial","Rural","Land","Development Sites"],
    conditions:["Modern","Refurbishment","Development"], tenure:"Mixed",
    niches:["Rural Property","Agricultural Land","Country Houses"],
    reach:"Regional", regions:["West Midlands","Worcestershire","Herefordshire"], area:"Worcestershire & West Midlands",
    successRate:70, premium:"Moderate", bargains:"Moderate",
    vendors:["Private","Probate","Corporate"], vendorPrimary:"Private & Estate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:3, historical:false, catalogue:true,
    highlights:["Strong rural and country property expertise","Good coverage of Worcestershire and Herefordshire","Regular auction calendar with diverse lots"]
  },
  {
    id:8, name:"Andrew Kelly", url:"https://www.andrewkelly.co.uk/",
    desc:"Lancashire-based auctioneers covering Rochdale, Bury and surrounding areas. Regular residential property auctions with good selection of terraced and semi-detached houses.",
    spec:"Residential", lots:["Residential Houses","Residential Flats","Buy-to-Let"],
    conditions:["Refurbishment","Modern"], tenure:"Mostly Vacant",
    niches:["Terraced Housing","Northern Residential"],
    reach:"Regional", regions:["North West","Lancashire","Greater Manchester"], area:"Rochdale & East Lancashire",
    successRate:68, premium:"Low", bargains:"Moderate",
    vendors:["Private","Probate","Lender"], vendorPrimary:"Private & Probate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:2, historical:false, catalogue:true,
    highlights:["Good source for affordable Northern residential stock","Competitive guide prices","Strong local market knowledge"]
  },
  {
    id:9, name:"Andrew Morris", url:"https://www.andrewmorris.co.uk/",
    desc:"Shropshire-based chartered surveyors with auctions covering Shrewsbury and surrounding areas. Handles residential, land and rural property through periodic auction sales.",
    spec:"Residential", lots:["Residential Houses","Land","Rural"],
    conditions:["Refurbishment","Modern"], tenure:"Mostly Vacant",
    niches:["Shropshire Property","Rural Residential"],
    reach:"Local", regions:["West Midlands","Shropshire"], area:"Shrewsbury & Shropshire",
    successRate:65, premium:"Low", bargains:"Moderate",
    vendors:["Private","Probate"], vendorPrimary:"Private & Probate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:2, historical:false, catalogue:false,
    highlights:["Deep local knowledge of Shropshire market","Good for rural property opportunities","Established local practice"]
  },
  {
    id:10, name:"Arnolds Keys", url:"https://www.arnoldskeys.com/",
    desc:"Leading Norfolk property firm with offices across the county. Regular property auctions featuring residential, commercial and rural lots throughout Norfolk and North Suffolk.",
    spec:"Mixed", lots:["Residential Houses","Commercial","Rural","Land","Agricultural"],
    conditions:["Modern","Refurbishment","Development"], tenure:"Mixed",
    niches:["Norfolk Property","Agricultural Land","Barn Conversions"],
    reach:"Regional", regions:["East Anglia","Norfolk","Suffolk"], area:"Norfolk & North Suffolk",
    successRate:72, premium:"Moderate", bargains:"Moderate",
    vendors:["Private","Probate","Corporate","Estate"], vendorPrimary:"Private & Estate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:3, historical:false, catalogue:true,
    highlights:["Leading Norfolk auctioneer with strong county coverage","Good mix of residential, commercial and rural lots","Strong agricultural and rural land expertise"]
  },
  {
    id:11, name:"Astleys", url:"https://www.astleys.com/",
    desc:"South Wales estate agents and auctioneers based in Swansea. Regular auctions of residential properties across the Swansea Bay and Gower areas.",
    spec:"Residential", lots:["Residential Houses","Residential Flats","Buy-to-Let"],
    conditions:["Refurbishment","Modern"], tenure:"Mostly Vacant",
    niches:["Swansea Property","Coastal Living"],
    reach:"Regional", regions:["Wales","South Wales","Swansea"], area:"Swansea & Gower",
    successRate:68, premium:"Low", bargains:"Moderate",
    vendors:["Private","Probate"], vendorPrimary:"Private & Probate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:3, historical:false, catalogue:true,
    highlights:["Strong Swansea Bay market presence","Good affordable residential opportunities","Local expertise in South Wales"]
  },
  {
    id:12, name:"Auction Estates", url:"https://www.auctionestates.co.uk/",
    desc:"Nottingham-based property auctioneers covering the East Midlands. Strong track record with residential and commercial lots, regular auction calendar and good online presence.",
    spec:"Mixed", lots:["Residential Houses","Commercial","Development Sites","Land","Buy-to-Let"],
    conditions:["Refurbishment","Development","Modern"], tenure:"Mixed",
    niches:["East Midlands Investment","Development Sites"],
    reach:"Regional", regions:["East Midlands","Nottingham","Derbyshire","Lincolnshire"], area:"Nottingham & East Midlands",
    successRate:75, premium:"Moderate", bargains:"Moderate",
    vendors:["Private","Lender","Probate","Corporate"], vendorPrimary:"Private & Lender",
    format:"Hybrid", buyerPrem:"1.2% + VAT", deposit:"10%", completion:28,
    dataRating:4, historical:true, catalogue:true,
    highlights:["Leading East Midlands auctioneer","Good mix of residential and commercial lots","Regular auction calendar with strong results","Good online catalogue and results data"]
  },
  {
    id:13, name:"Auction House UK", url:"https://www.auctionhouse.co.uk/",
    desc:"The UK's largest property auction network with franchise partners nationwide. Conducts more residential property auctions than any other UK auctioneer, with both room and online options.",
    spec:"Mixed", lots:["Residential Houses","Commercial","Land","Development Sites","Buy-to-Let","HMO"],
    conditions:["Modern","Refurbishment","Development","Derelict"], tenure:"Mixed",
    niches:["Residential Investment","Buy-to-Let","HMO","Development"],
    reach:"National", regions:["National","London","North West","West Midlands","Yorkshire","South West","East Midlands","Wales"], area:"Nationwide via franchise network",
    successRate:77, premium:"Moderate", bargains:"Moderate",
    vendors:["Private","Lender","Probate","Corporate","Developer"], vendorPrimary:"All vendor types",
    format:"Hybrid", buyerPrem:"Varies by branch (0-2%)", deposit:"10%", completion:28,
    dataRating:4, historical:true, catalogue:true,
    highlights:["UK's largest property auction network","More lots sold than any other UK auctioneer","National coverage through local franchise experts","Good historical results data online","Wide variety of lot types and price ranges"]
  },
  {
    id:14, name:"Austin Gray", url:"https://www.austingray.co.uk/",
    desc:"Brighton-based estate agents offering property auction services across Sussex and the South Coast. Regular sales of residential flats, houses and some commercial property.",
    spec:"Residential", lots:["Residential Flats","Residential Houses","Buy-to-Let"],
    conditions:["Modern","Refurbishment"], tenure:"Mostly Vacant",
    niches:["Brighton Property","South Coast"],
    reach:"Regional", regions:["South East","Sussex","Brighton"], area:"Brighton & Sussex",
    successRate:70, premium:"Moderate", bargains:"Moderate",
    vendors:["Private","Probate"], vendorPrimary:"Private Vendors",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:3, historical:false, catalogue:true,
    highlights:["Strong presence in Brighton and Sussex market","Good residential opportunities on the South Coast"]
  },
  {
    id:15, name:"Baker Wynne & Wilson", url:"https://www.bakerwynneandwilson.co.uk/",
    desc:"Cheshire and Shropshire-based estate agents with periodic auction sales. Covers residential and rural property in Nantwich, Whitchurch and the surrounding rural areas.",
    spec:"Residential", lots:["Residential Houses","Rural","Land"],
    conditions:["Refurbishment","Modern"], tenure:"Mostly Vacant",
    niches:["Cheshire Rural","Country Properties"],
    reach:"Local", regions:["North West","Cheshire","Shropshire"], area:"Nantwich & South Cheshire",
    successRate:65, premium:"Low", bargains:"Moderate",
    vendors:["Private","Probate"], vendorPrimary:"Private & Probate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:2, historical:false, catalogue:false,
    highlights:["Established South Cheshire presence","Good for rural and period property"]
  },
  {
    id:16, name:"Barnett Ross", url:"https://www.barnettross.co.uk/",
    desc:"London-based commercial and residential property auctioneers. Specialist in North London and Greater London auction sales with a strong commercial investment portfolio.",
    spec:"Mixed", lots:["Commercial Investment","Residential","Mixed Use","Development Sites"],
    conditions:["Modern","Refurbishment","Development"], tenure:"Mixed",
    niches:["London Commercial","North London Property","Mixed Use Investment"],
    reach:"Regional", regions:["London","North London","Greater London"], area:"London & Home Counties",
    successRate:72, premium:"High", bargains:"Low",
    vendors:["Private","Corporate","Lender"], vendorPrimary:"Private & Corporate",
    format:"Room", buyerPrem:"2% + VAT", deposit:"10%", completion:28,
    dataRating:3, historical:false, catalogue:true,
    highlights:["Strong London commercial auction presence","Good source of North London investment lots","Regular auction calendar"]
  },
  {
    id:17, name:"BidX1", url:"https://bidx1.com/",
    desc:"Leading online property auction platform operating across the UK, Ireland and internationally. Technology-driven approach with transparent bidding process for commercial and residential lots.",
    spec:"Mixed", lots:["Commercial Investment","Residential","Development Sites","Mixed Use","Land"],
    conditions:["Modern","Refurbishment","Development"], tenure:"Mixed",
    niches:["Online Auctions","Cross-border Investment","Commercial Investment"],
    reach:"National", regions:["National","London","Ireland","International"], area:"UK, Ireland & International",
    successRate:70, premium:"Moderate", bargains:"Moderate",
    vendors:["Corporate","Lender","Institutional","Private"], vendorPrimary:"Corporate & Lender",
    format:"Online", buyerPrem:"2% + VAT", deposit:"10%", completion:28,
    dataRating:4, historical:true, catalogue:true,
    highlights:["Leading online property auction platform","Transparent digital bidding process","Strong commercial and mixed-use lots","Good international and cross-border opportunities","Excellent data transparency and results history"]
  },
  {
    id:18, name:"Bond Oxborough Phillips", url:"https://www.bondoxboroughphillips.co.uk/",
    desc:"Devon and Cornwall estate agents with periodic auction sales of residential and rural properties across the South West peninsula. Covers Bideford, Barnstaple and North Devon.",
    spec:"Residential", lots:["Residential Houses","Rural","Land","Holiday Lets"],
    conditions:["Refurbishment","Modern"], tenure:"Mostly Vacant",
    niches:["Devon Property","Holiday Lets","Rural South West"],
    reach:"Regional", regions:["South West","Devon","Cornwall"], area:"North Devon & Cornwall",
    successRate:68, premium:"Moderate", bargains:"Moderate",
    vendors:["Private","Probate","Estate"], vendorPrimary:"Private & Probate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:2, historical:false, catalogue:true,
    highlights:["Good coverage of North Devon and Cornwall","Holiday let and rural property expertise","Established South West practice"]
  },
  {
    id:19, name:"Bond Wolfe", url:"https://www.bondwolfe.com/",
    desc:"Leading Birmingham and West Midlands auctioneer, one of the most active regional auction houses in the UK. Regular high-volume sales of residential, commercial and land across the Midlands.",
    spec:"Mixed", lots:["Residential Houses","Commercial","Land","Development Sites","Buy-to-Let","HMO"],
    conditions:["Modern","Refurbishment","Development","Derelict"], tenure:"Mixed",
    niches:["Birmingham Property","West Midlands Investment","HMO","Development"],
    reach:"Regional", regions:["West Midlands","Birmingham","Staffordshire","Warwickshire"], area:"Birmingham & West Midlands",
    successRate:80, premium:"Moderate", bargains:"Moderate",
    vendors:["Private","Lender","Probate","Corporate","Developer"], vendorPrimary:"All vendor types",
    format:"Hybrid", buyerPrem:"1.2% + VAT", deposit:"10%", completion:28,
    dataRating:4, historical:true, catalogue:true,
    highlights:["Leading West Midlands auctioneer by volume","Excellent success rates","Wide variety of lot types including HMO and development","Good historical results data","Strong local market knowledge in Birmingham"]
  },
  {
    id:20, name:"Boot & Son", url:"https://www.bootandson.com/",
    desc:"Staffordshire-based estate agents and auctioneers covering Leek, Stoke-on-Trent and the Staffordshire Moorlands. Periodic residential property auction sales.",
    spec:"Residential", lots:["Residential Houses","Land"],
    conditions:["Refurbishment","Modern"], tenure:"Mostly Vacant",
    niches:["Staffordshire Moorlands","Rural Residential"],
    reach:"Local", regions:["West Midlands","Staffordshire"], area:"Leek & Staffordshire Moorlands",
    successRate:65, premium:"Low", bargains:"Moderate",
    vendors:["Private","Probate"], vendorPrimary:"Private & Probate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:2, historical:false, catalogue:false,
    highlights:["Local Staffordshire Moorlands specialist","Affordable residential lots","Established local practice"]
  },
  {
    id:21, name:"Boultons", url:"https://www.boultons.com/",
    desc:"South Yorkshire auctioneers based in Doncaster. Regular property auction sales covering residential and some commercial properties across South and West Yorkshire.",
    spec:"Residential", lots:["Residential Houses","Residential Flats","Buy-to-Let"],
    conditions:["Refurbishment","Modern"], tenure:"Mixed",
    niches:["Yorkshire Buy-to-Let","Northern Residential"],
    reach:"Regional", regions:["Yorkshire","South Yorkshire","Doncaster"], area:"Doncaster & South Yorkshire",
    successRate:68, premium:"Low", bargains:"Moderate",
    vendors:["Private","Probate","Lender"], vendorPrimary:"Private & Probate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:2, historical:false, catalogue:true,
    highlights:["Strong South Yorkshire market presence","Good buy-to-let yield opportunities","Affordable residential stock"]
  },
  {
    id:22, name:"Bowen Son & Watson", url:"https://www.bowenson.co.uk/",
    desc:"Shropshire and Mid Wales estate agents and auctioneers. Covers Oswestry, Welshpool and the Welsh Borders with residential, rural and agricultural property auctions.",
    spec:"Residential", lots:["Residential Houses","Rural","Agricultural","Land"],
    conditions:["Refurbishment","Modern"], tenure:"Mostly Vacant",
    niches:["Welsh Borders","Rural Smallholdings","Agricultural"],
    reach:"Regional", regions:["West Midlands","Shropshire","Wales","Mid Wales"], area:"Oswestry & Welsh Borders",
    successRate:65, premium:"Low", bargains:"Moderate",
    vendors:["Private","Probate","Estate"], vendorPrimary:"Private & Estate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:2, historical:false, catalogue:false,
    highlights:["Strong Welsh Borders coverage","Rural and agricultural property expertise","Cross-border Shropshire/Wales lots"]
  },
  {
    id:23, name:"Bradleys", url:"https://www.bradleysauctions.co.uk/",
    desc:"Devon-based auctioneers covering Exeter, Plymouth and across Devon and Cornwall. Regular residential property auction sales with strong South West coverage.",
    spec:"Residential", lots:["Residential Houses","Residential Flats","Holiday Lets","Land"],
    conditions:["Refurbishment","Modern"], tenure:"Mostly Vacant",
    niches:["Devon Property","Holiday Lets","South West Residential"],
    reach:"Regional", regions:["South West","Devon","Cornwall"], area:"Exeter, Plymouth & Devon",
    successRate:70, premium:"Moderate", bargains:"Moderate",
    vendors:["Private","Probate"], vendorPrimary:"Private & Probate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:3, historical:false, catalogue:true,
    highlights:["Strong Devon and Cornwall coverage","Good holiday let opportunities","Regular auction calendar"]
  },
  {
    id:24, name:"Bramleys", url:"https://www.bramleys.com/",
    desc:"West Yorkshire chartered surveyors based in Huddersfield. Conduct periodic property auctions featuring residential lots across Huddersfield, Halifax and the wider West Yorkshire area.",
    spec:"Residential", lots:["Residential Houses","Residential Flats","Buy-to-Let"],
    conditions:["Refurbishment","Modern"], tenure:"Mixed",
    niches:["West Yorkshire Residential","Terraced Housing"],
    reach:"Regional", regions:["Yorkshire","West Yorkshire","Huddersfield"], area:"Huddersfield & West Yorkshire",
    successRate:68, premium:"Low", bargains:"Moderate",
    vendors:["Private","Probate"], vendorPrimary:"Private & Probate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:2, historical:false, catalogue:true,
    highlights:["Local West Yorkshire market expertise","Affordable residential investment stock","Established Huddersfield practice"]
  },
  {
    id:25, name:"BRG Gibson Auctions", url:"https://www.brggibson.co.uk/",
    desc:"Scottish property auctioneers offering residential property auctions across central Scotland. Covers Glasgow, Edinburgh and surrounding areas.",
    spec:"Residential", lots:["Residential Houses","Residential Flats","Buy-to-Let"],
    conditions:["Refurbishment","Modern"], tenure:"Mostly Vacant",
    niches:["Scottish Residential","Glasgow Property"],
    reach:"Regional", regions:["Scotland","Glasgow","Central Scotland"], area:"Central Scotland",
    successRate:65, premium:"Low", bargains:"Moderate",
    vendors:["Private","Probate","Lender"], vendorPrimary:"Private & Lender",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:2, historical:false, catalogue:true,
    highlights:["Scottish property auction specialist","Good Glasgow and Central Scotland coverage","Competitive Scottish residential pricing"]
  },
  {
    id:26, name:"Brights", url:"https://www.brightsauctions.co.uk/",
    desc:"South Wales property auctioneers covering Bridgend, Cardiff and the wider Valleys region. Regular residential auction sales with good local market knowledge.",
    spec:"Residential", lots:["Residential Houses","Residential Flats","Buy-to-Let"],
    conditions:["Refurbishment","Modern"], tenure:"Mixed",
    niches:["South Wales Valleys","Buy-to-Let"],
    reach:"Regional", regions:["Wales","South Wales","Bridgend","Cardiff"], area:"Bridgend, Cardiff & South Wales",
    successRate:68, premium:"Low", bargains:"Moderate",
    vendors:["Private","Probate","Lender"], vendorPrimary:"Private & Probate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:3, historical:false, catalogue:true,
    highlights:["Strong South Wales Valleys presence","Good buy-to-let opportunities","Affordable residential stock"]
  },
  {
    id:27, name:"Brown & Co", url:"https://www.brown-co.com/",
    desc:"Major rural and agricultural property consultancy with strong auction practice across East Anglia and the East Midlands. Specialists in farmland, rural estates, and country property.",
    spec:"Rural/Land", lots:["Agricultural","Land","Rural","Residential Houses","Development Sites"],
    conditions:["Modern","Refurbishment","Development"], tenure:"Mixed",
    niches:["Agricultural Land","Rural Estates","Farmland","Country Houses"],
    reach:"Regional", regions:["East Anglia","East Midlands","Norfolk","Lincolnshire"], area:"East Anglia & East Midlands",
    successRate:72, premium:"Moderate", bargains:"Moderate",
    vendors:["Private","Estate","Corporate"], vendorPrimary:"Estate & Private",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:3, historical:false, catalogue:true,
    highlights:["Leading rural and agricultural auctioneers","Strong farmland and country estate expertise","Good East Anglia and Midlands coverage","Excellent for land opportunities"]
  },
  {
    id:28, name:"Bury & Hilton", url:"https://www.buryandhilton.co.uk/",
    desc:"Staffordshire estate agents and auctioneers covering Leek, Uttoxeter and the Staffordshire Moorlands. Periodic property auctions of residential and rural lots.",
    spec:"Residential", lots:["Residential Houses","Rural","Land"],
    conditions:["Refurbishment","Modern"], tenure:"Mostly Vacant",
    niches:["Staffordshire Moorlands","Rural Residential"],
    reach:"Local", regions:["West Midlands","Staffordshire","Derbyshire"], area:"Leek & Staffordshire Moorlands",
    successRate:65, premium:"Low", bargains:"Moderate",
    vendors:["Private","Probate"], vendorPrimary:"Private & Probate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:2, historical:false, catalogue:false,
    highlights:["Local Staffordshire and Derbyshire expertise","Affordable rural residential lots"]
  },
  {
    id:29, name:"Butters John Bee", url:"https://www.bjb.co.uk/",
    desc:"Staffordshire and Cheshire estate agents with regular property auction sales. Covers Stoke-on-Trent, Crewe, Newcastle-under-Lyme and surrounding areas with a strong residential focus.",
    spec:"Residential", lots:["Residential Houses","Residential Flats","Buy-to-Let","Land"],
    conditions:["Refurbishment","Modern"], tenure:"Mixed",
    niches:["Staffordshire Residential","Buy-to-Let Yields"],
    reach:"Regional", regions:["West Midlands","Staffordshire","Cheshire","North West"], area:"Stoke-on-Trent & Cheshire",
    successRate:70, premium:"Low", bargains:"Moderate",
    vendors:["Private","Probate","Lender"], vendorPrimary:"Private & Probate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:3, historical:false, catalogue:true,
    highlights:["Strong Stoke-on-Trent and North Staffordshire coverage","Good affordable residential buy-to-let stock","Regular auction calendar"]
  },
  {
    id:30, name:"Carter Jonas", url:"https://www.carterjonas.co.uk/",
    desc:"National property consultancy offering auction services across England. Strong in rural, residential and commercial sectors with offices from Cambridge to Oxford and beyond.",
    spec:"Mixed", lots:["Residential Houses","Rural","Commercial","Land","Development Sites"],
    conditions:["Modern","Refurbishment","Development"], tenure:"Mixed",
    niches:["Rural Property","Country Houses","Agricultural Land","Strategic Land"],
    reach:"National", regions:["National","East Anglia","South East","South West","Midlands"], area:"England-wide",
    successRate:72, premium:"Moderate", bargains:"Moderate",
    vendors:["Private","Estate","Corporate","Institutional"], vendorPrimary:"Private & Estate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:4, historical:true, catalogue:true,
    highlights:["National consultancy with strong auction practice","Excellent rural and country property expertise","Good coverage from Cambridge to Cotswolds","High-quality lot selection"]
  },
  {
    id:31, name:"Charles Darrow", url:"https://www.charlesdarrow.co.uk/",
    desc:"South Coast property auctioneers covering Hampshire, Dorset and the Isle of Wight. Regular residential auction sales with local expertise.",
    spec:"Residential", lots:["Residential Houses","Residential Flats","Holiday Lets"],
    conditions:["Modern","Refurbishment"], tenure:"Mostly Vacant",
    niches:["South Coast Property","Hampshire Residential"],
    reach:"Regional", regions:["South East","Hampshire","Dorset","Isle of Wight"], area:"Hampshire & South Coast",
    successRate:68, premium:"Moderate", bargains:"Moderate",
    vendors:["Private","Probate"], vendorPrimary:"Private & Probate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:2, historical:false, catalogue:true,
    highlights:["Good South Coast and Hampshire coverage","Residential specialist"]
  },
  {
    id:32, name:"Cheffins", url:"https://www.cheffins.co.uk/",
    desc:"Cambridge-based auctioneers and estate agents. Leading East Anglian property auctioneer with strong residential, rural and land auction practice across Cambridgeshire and beyond.",
    spec:"Mixed", lots:["Residential Houses","Rural","Agricultural","Land","Commercial","Development Sites"],
    conditions:["Modern","Refurbishment","Development"], tenure:"Mixed",
    niches:["Cambridge Property","Agricultural Land","Rural Estates","Development Land"],
    reach:"Regional", regions:["East Anglia","Cambridgeshire","Suffolk","Norfolk"], area:"Cambridge & East Anglia",
    successRate:75, premium:"Moderate", bargains:"Moderate",
    vendors:["Private","Estate","Probate","Corporate"], vendorPrimary:"Private & Estate",
    format:"Hybrid", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:4, historical:true, catalogue:true,
    highlights:["Leading Cambridge and East Anglia auctioneer","Excellent rural and agricultural expertise","Strong residential and commercial auction practice","Good data transparency with results available"]
  },
  {
    id:33, name:"Clarke & Simpson", url:"https://www.clarke-simpson.co.uk/",
    desc:"Suffolk-based chartered surveyors and estate agents with regular property auctions covering residential and rural lots across Suffolk and East Anglia.",
    spec:"Residential", lots:["Residential Houses","Rural","Land","Agricultural"],
    conditions:["Refurbishment","Modern"], tenure:"Mostly Vacant",
    niches:["Suffolk Property","Rural Residential","Barn Conversions"],
    reach:"Regional", regions:["East Anglia","Suffolk"], area:"Suffolk",
    successRate:68, premium:"Moderate", bargains:"Moderate",
    vendors:["Private","Probate","Estate"], vendorPrimary:"Private & Probate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:3, historical:false, catalogue:true,
    highlights:["Strong Suffolk market presence","Good rural and residential mix","Established East Anglian auctioneer"]
  },
  {
    id:34, name:"Clarke Gammon Wellers", url:"https://www.cgwsurveyors.co.uk/",
    desc:"Surrey and Hampshire chartered surveyors with periodic property auction sales. Covers Guildford, Haslemere and the surrounding Surrey Hills area.",
    spec:"Residential", lots:["Residential Houses","Land","Development Sites"],
    conditions:["Modern","Refurbishment","Development"], tenure:"Mostly Vacant",
    niches:["Surrey Property","Country Living"],
    reach:"Regional", regions:["South East","Surrey","Hampshire"], area:"Guildford & Surrey Hills",
    successRate:70, premium:"Moderate", bargains:"Low",
    vendors:["Private","Probate"], vendorPrimary:"Private & Probate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:3, historical:false, catalogue:true,
    highlights:["Strong Surrey and Hampshire expertise","Premium South East location","Good development site opportunities"]
  },
  {
    id:35, name:"Clee Tompkinson Francis", url:"https://www.ctf-estates.co.uk/",
    desc:"South Wales estate agents covering Swansea, Llanelli and the wider South and West Wales area. Regular property auctions featuring residential and some commercial lots.",
    spec:"Residential", lots:["Residential Houses","Residential Flats","Commercial","Land"],
    conditions:["Refurbishment","Modern"], tenure:"Mostly Vacant",
    niches:["South Wales Residential","West Wales Property"],
    reach:"Regional", regions:["Wales","South Wales","West Wales","Swansea"], area:"Swansea & West Wales",
    successRate:68, premium:"Low", bargains:"Moderate",
    vendors:["Private","Probate","Lender"], vendorPrimary:"Private & Probate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:3, historical:false, catalogue:true,
    highlights:["Good South and West Wales coverage","Affordable residential lots","Regular auction calendar"]
  },
  {
    id:36, name:"Clive Emson", url:"https://www.cliveemson.co.uk/",
    desc:"One of the South of England's largest and most established auctioneers. Regular high-volume auctions across the South East, South West and London with excellent success rates and data.",
    spec:"Mixed", lots:["Residential Houses","Land","Development Sites","Commercial","Mixed Use","Agricultural"],
    conditions:["Modern","Refurbishment","Development","Derelict"], tenure:"Mixed",
    niches:["Land & Development","South East Investment","Residential Refurb"],
    reach:"Regional", regions:["South East","South West","London","Kent","Sussex","Hampshire","Devon","Cornwall"], area:"South of England",
    successRate:78, premium:"Moderate", bargains:"Moderate",
    vendors:["Private","Lender","Probate","Corporate","Developer"], vendorPrimary:"All vendor types",
    format:"Hybrid", buyerPrem:"2% + VAT", deposit:"10%", completion:20,
    dataRating:4, historical:true, catalogue:true,
    highlights:["One of the largest South of England auctioneers","Excellent success rates consistently","Strong land and development site offering","Good data transparency with historical results","Regular eight-auction annual calendar"]
  },
  {
    id:37, name:"Clough & Co", url:"https://www.clough-co.co.uk/",
    desc:"Lancashire-based estate agents conducting periodic property auctions in the Blackpool and Fylde Coast area. Residential properties at competitive guide prices.",
    spec:"Residential", lots:["Residential Houses","Residential Flats","Buy-to-Let"],
    conditions:["Refurbishment","Modern"], tenure:"Mostly Vacant",
    niches:["Blackpool Property","Fylde Coast"],
    reach:"Local", regions:["North West","Lancashire","Blackpool"], area:"Blackpool & Fylde Coast",
    successRate:65, premium:"Low", bargains:"High",
    vendors:["Private","Probate","Lender"], vendorPrimary:"Private & Lender",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:2, historical:false, catalogue:false,
    highlights:["Good source of affordable Blackpool stock","High bargain incidence","Coastal buy-to-let opportunities"]
  },
  {
    id:38, name:"Cottons", url:"https://www.cottons.co.uk/",
    desc:"Birmingham-based commercial and residential property auctioneers. One of the Midlands' most established auction houses with regular sales of investment and development property.",
    spec:"Mixed", lots:["Commercial Investment","Residential","Development Sites","Land","Mixed Use"],
    conditions:["Modern","Refurbishment","Development"], tenure:"Mixed",
    niches:["Birmingham Commercial","Midlands Investment","Development Sites"],
    reach:"Regional", regions:["West Midlands","Birmingham","East Midlands"], area:"Birmingham & Midlands",
    successRate:75, premium:"Moderate", bargains:"Moderate",
    vendors:["Corporate","Lender","Private","Developer"], vendorPrimary:"Corporate & Lender",
    format:"Hybrid", buyerPrem:"1.5% + VAT", deposit:"10%", completion:28,
    dataRating:4, historical:true, catalogue:true,
    highlights:["Established Midlands commercial auctioneer","Strong investment property offering","Good development site and land lots","Regular auction calendar with good results data"]
  },
  {
    id:39, name:"Countrywide Property Auctions", url:"https://www.barnardmarcusauctions.co.uk/",
    desc:"National property auctioneer operating under the Barnard Marcus brand. Regular high-volume London and national auction sales covering residential, commercial and investment property.",
    spec:"Mixed", lots:["Residential Houses","Residential Flats","Commercial","Mixed Use","Development Sites","Buy-to-Let"],
    conditions:["Modern","Refurbishment","Development"], tenure:"Mixed",
    niches:["London Residential","National Investment","Development"],
    reach:"National", regions:["London","National","South East","Midlands","North"], area:"London & Nationwide",
    successRate:75, premium:"Moderate", bargains:"Moderate",
    vendors:["Lender","Private","Corporate","Probate"], vendorPrimary:"Lender & Private",
    format:"Room", buyerPrem:"2% + VAT", deposit:"10%", completion:20,
    dataRating:4, historical:true, catalogue:true,
    highlights:["National auction presence under Barnard Marcus brand","Regular high-volume London sales","Strong lender and institutional vendor base","Good variety across price ranges"]
  },
  {
    id:40, name:"David James", url:"https://www.davidjamesandpartners.co.uk/",
    desc:"Gloucestershire-based estate agents covering the Cotswolds and Forest of Dean. Periodic property auction sales of residential and rural properties.",
    spec:"Residential", lots:["Residential Houses","Rural","Land"],
    conditions:["Modern","Refurbishment"], tenure:"Mostly Vacant",
    niches:["Cotswolds Property","Forest of Dean","Country Residential"],
    reach:"Local", regions:["South West","Gloucestershire","Cotswolds"], area:"Gloucestershire & Cotswolds",
    successRate:68, premium:"Moderate", bargains:"Moderate",
    vendors:["Private","Probate"], vendorPrimary:"Private & Probate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:2, historical:false, catalogue:false,
    highlights:["Cotswolds and Gloucestershire specialist","Good country and rural residential lots"]
  },
  {
    id:41, name:"Dawsons", url:"https://www.dawsonsproperty.co.uk/",
    desc:"Swansea-based estate agents with regular property auction sales across South Wales. Strong residential coverage of the Swansea, Neath and Llanelli areas.",
    spec:"Residential", lots:["Residential Houses","Residential Flats","Buy-to-Let"],
    conditions:["Refurbishment","Modern"], tenure:"Mixed",
    niches:["Swansea Property","South Wales Buy-to-Let"],
    reach:"Regional", regions:["Wales","South Wales","Swansea"], area:"Swansea & South Wales",
    successRate:70, premium:"Low", bargains:"Moderate",
    vendors:["Private","Probate","Lender"], vendorPrimary:"Private & Probate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:3, historical:false, catalogue:true,
    highlights:["Strong Swansea and South Wales presence","Good buy-to-let yield opportunities","Regular auction calendar"]
  },
  {
    id:42, name:"Dedman Gray", url:"https://www.dedmangray.co.uk/",
    desc:"Essex-based auctioneers covering Southend, Basildon, Chelmsford and wider Essex. Regular residential property auctions with strong local market knowledge.",
    spec:"Residential", lots:["Residential Houses","Residential Flats","Buy-to-Let","Land"],
    conditions:["Refurbishment","Modern"], tenure:"Mostly Vacant",
    niches:["Essex Residential","Thames Gateway"],
    reach:"Regional", regions:["South East","Essex","Southend"], area:"Southend & Essex",
    successRate:70, premium:"Moderate", bargains:"Moderate",
    vendors:["Private","Probate","Lender"], vendorPrimary:"Private & Probate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:3, historical:false, catalogue:true,
    highlights:["Strong Essex market presence","Good residential auction track record","Thames Gateway and Southend opportunities"]
  },
  {
    id:43, name:"Drivers & Norris", url:"https://www.drivers.co.uk/",
    desc:"North London estate agents and auctioneers established in 1860. Regular property auction sales of residential and commercial lots in Islington, Holloway and wider North London.",
    spec:"Mixed", lots:["Residential Houses","Residential Flats","Commercial","Mixed Use"],
    conditions:["Modern","Refurbishment"], tenure:"Mixed",
    niches:["North London Property","Islington Investment","London Commercial"],
    reach:"Regional", regions:["London","North London","Islington"], area:"North London & Islington",
    successRate:72, premium:"High", bargains:"Low",
    vendors:["Private","Corporate","Probate"], vendorPrimary:"Private & Corporate",
    format:"Room", buyerPrem:"1% + VAT", deposit:"10%", completion:28,
    dataRating:3, historical:false, catalogue:true,
    highlights:["Established since 1860","Strong North London and Islington presence","Good commercial and mixed-use lots","Premium London location"]
  },
  {
    id:44, name:"Durrants", url:"https://www.durrants.com/",
    desc:"Norfolk and Suffolk estate agents with periodic property auctions covering residential and rural lots in Beccles, Halesworth and the wider Waveney Valley area.",
    spec:"Residential", lots:["Residential Houses","Rural","Agricultural","Land"],
    conditions:["Refurbishment","Modern"], tenure:"Mostly Vacant",
    niches:["Norfolk/Suffolk Border","Rural Property","Period Cottages"],
    reach:"Regional", regions:["East Anglia","Norfolk","Suffolk"], area:"Waveney Valley & North Suffolk",
    successRate:68, premium:"Moderate", bargains:"Moderate",
    vendors:["Private","Probate","Estate"], vendorPrimary:"Private & Probate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:2, historical:false, catalogue:true,
    highlights:["Strong Norfolk/Suffolk border coverage","Good rural and period property lots","Established regional practice"]
  },
  {
    id:45, name:"Earles", url:"https://www.earlesproperty.co.uk/",
    desc:"East Yorkshire property auctioneers based in Hull. Regular residential auction sales covering Hull, East Riding and surrounding areas with affordable investment stock.",
    spec:"Residential", lots:["Residential Houses","Residential Flats","Buy-to-Let"],
    conditions:["Refurbishment","Modern"], tenure:"Mixed",
    niches:["Hull Property","East Yorkshire Buy-to-Let","Affordable Housing"],
    reach:"Regional", regions:["Yorkshire","East Yorkshire","Hull"], area:"Hull & East Yorkshire",
    successRate:65, premium:"Low", bargains:"High",
    vendors:["Private","Probate","Lender"], vendorPrimary:"Private & Lender",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:2, historical:false, catalogue:true,
    highlights:["Good source of affordable Hull and East Yorkshire stock","Strong buy-to-let yield potential","High bargain incidence at auction"]
  },
  {
    id:46, name:"Edward Mellor Auctions", url:"https://www.edwardmellor.co.uk/auctions/",
    desc:"Major Manchester and North West auctioneer. One of the largest regional auction houses in England with regular high-volume sales across Greater Manchester and beyond.",
    spec:"Mixed", lots:["Residential Houses","Commercial","Development Sites","Land","Buy-to-Let","HMO"],
    conditions:["Modern","Refurbishment","Development","Derelict"], tenure:"Mixed",
    niches:["Manchester Property","North West Investment","HMO","Development"],
    reach:"Regional", regions:["North West","Manchester","Greater Manchester","Lancashire","Cheshire"], area:"Manchester & Greater Manchester",
    successRate:78, premium:"Moderate", bargains:"Moderate",
    vendors:["Private","Lender","Probate","Corporate","Developer"], vendorPrimary:"All vendor types",
    format:"Hybrid", buyerPrem:"1% + VAT", deposit:"10%", completion:28,
    dataRating:4, historical:true, catalogue:true,
    highlights:["One of the largest North West auctioneers","Excellent success rates","Strong Manchester pipeline","Wide variety of lot types including HMO","Good data transparency and online results"]
  },
  {
    id:47, name:"Evans Bros", url:"https://www.evansbros.co.uk/",
    desc:"West Wales estate agents and auctioneers covering Llanybydder, Carmarthen and surrounding Ceredigion countryside. Handles rural, agricultural and residential property.",
    spec:"Rural/Land", lots:["Agricultural","Rural","Land","Residential Houses"],
    conditions:["Refurbishment","Modern"], tenure:"Mostly Vacant",
    niches:["West Wales Rural","Smallholdings","Agricultural Land"],
    reach:"Local", regions:["Wales","West Wales","Ceredigion","Carmarthenshire"], area:"West Wales & Ceredigion",
    successRate:65, premium:"Low", bargains:"Moderate",
    vendors:["Private","Probate","Estate"], vendorPrimary:"Private & Estate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:1, historical:false, catalogue:false,
    highlights:["West Wales rural and agricultural specialist","Good smallholding and farm opportunities","Deep local knowledge"]
  },
  {
    id:48, name:"Feather Smailes & Scales", url:"https://www.fssurveyors.co.uk/",
    desc:"Harrogate-based chartered surveyors with periodic property auctions covering North Yorkshire. Residential and rural properties across the Harrogate, York and North Yorkshire area.",
    spec:"Residential", lots:["Residential Houses","Rural","Land"],
    conditions:["Modern","Refurbishment"], tenure:"Mostly Vacant",
    niches:["Harrogate Property","North Yorkshire Residential"],
    reach:"Regional", regions:["Yorkshire","North Yorkshire","Harrogate","York"], area:"Harrogate & North Yorkshire",
    successRate:68, premium:"Moderate", bargains:"Moderate",
    vendors:["Private","Probate"], vendorPrimary:"Private & Probate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:3, historical:false, catalogue:true,
    highlights:["Strong North Yorkshire and Harrogate expertise","Good residential and rural lots","Established chartered surveyor practice"]
  },
  {
    id:49, name:"Fidler Taylor", url:"https://www.fidlertaylor.co.uk/",
    desc:"Derbyshire chartered surveyors covering Ashbourne, Bakewell and the Peak District. Handles residential, rural and land auctions in the Derbyshire Dales area.",
    spec:"Residential", lots:["Residential Houses","Rural","Land","Agricultural"],
    conditions:["Refurbishment","Modern"], tenure:"Mostly Vacant",
    niches:["Peak District Property","Derbyshire Dales","Rural Cottages"],
    reach:"Local", regions:["East Midlands","Derbyshire","Peak District"], area:"Ashbourne & Peak District",
    successRate:65, premium:"Moderate", bargains:"Moderate",
    vendors:["Private","Probate","Estate"], vendorPrimary:"Private & Estate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:2, historical:false, catalogue:false,
    highlights:["Peak District and Derbyshire Dales specialist","Good rural cottage and period property opportunities"]
  },
  {
    id:50, name:"First for Auctions", url:"https://www.firstforauctions.co.uk/",
    desc:"North West property auctioneers offering residential and commercial lots across Lancashire, Greater Manchester and Merseyside through both room and online auctions.",
    spec:"Residential", lots:["Residential Houses","Residential Flats","Buy-to-Let","Commercial"],
    conditions:["Refurbishment","Modern"], tenure:"Mixed",
    niches:["North West Residential","Buy-to-Let Yields"],
    reach:"Regional", regions:["North West","Lancashire","Manchester","Merseyside"], area:"North West England",
    successRate:70, premium:"Moderate", bargains:"Moderate",
    vendors:["Private","Lender","Probate"], vendorPrimary:"Private & Lender",
    format:"Hybrid", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:3, historical:false, catalogue:true,
    highlights:["Good North West England coverage","Room and online bidding options","Competitive residential lots"]
  },
  {
    id:51, name:"Fisher German", url:"https://www.fishergerman.co.uk/",
    desc:"National rural property consultancy with strong auction practice. Specialists in agricultural land, rural estates, and commercial rural property across the Midlands and nationally.",
    spec:"Rural/Land", lots:["Agricultural","Land","Rural","Development Sites","Commercial"],
    conditions:["Modern","Development"], tenure:"Mixed",
    niches:["Agricultural Land","Rural Estates","Strategic Land","Renewable Energy Sites"],
    reach:"National", regions:["National","East Midlands","West Midlands","East Anglia"], area:"Midlands & National",
    successRate:72, premium:"Moderate", bargains:"Moderate",
    vendors:["Corporate","Estate","Institutional","Private"], vendorPrimary:"Estate & Corporate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:4, historical:true, catalogue:true,
    highlights:["Leading national rural property consultancy","Excellent agricultural and strategic land expertise","Good data transparency","Strong institutional and estate vendor base"]
  },
  {
    id:52, name:"Fox Grant", url:"https://www.foxgrant.co.uk/",
    desc:"South West rural property specialists covering Dorset, Somerset and Devon. Handles rural, agricultural and residential property sales and auctions.",
    spec:"Rural/Land", lots:["Rural","Agricultural","Land","Residential Houses"],
    conditions:["Modern","Refurbishment"], tenure:"Mostly Vacant",
    niches:["Dorset Rural","Farmland","Country Houses"],
    reach:"Regional", regions:["South West","Dorset","Somerset","Devon"], area:"Dorset & South West",
    successRate:68, premium:"Moderate", bargains:"Moderate",
    vendors:["Private","Estate"], vendorPrimary:"Private & Estate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:2, historical:false, catalogue:false,
    highlights:["South West rural and agricultural specialist","Good country property and land opportunities"]
  },
  {
    id:53, name:"Future Property Auctions", url:"https://www.futurepropertyauctions.co.uk/",
    desc:"Glasgow-based property auctioneers offering residential lots across central Scotland. Online and room auction options for Scottish residential investment properties.",
    spec:"Residential", lots:["Residential Houses","Residential Flats","Buy-to-Let"],
    conditions:["Refurbishment","Modern"], tenure:"Mixed",
    niches:["Glasgow Property","Scottish Residential","Buy-to-Let"],
    reach:"Regional", regions:["Scotland","Glasgow","Central Scotland"], area:"Glasgow & Central Scotland",
    successRate:70, premium:"Low", bargains:"Moderate",
    vendors:["Private","Lender","Probate"], vendorPrimary:"Private & Lender",
    format:"Online", buyerPrem:"2.5% + VAT", deposit:"10%", completion:28,
    dataRating:3, historical:false, catalogue:true,
    highlights:["Good Glasgow and central Scotland coverage","Online bidding platform","Affordable Scottish residential stock"]
  },
  {
    id:54, name:"G Herbert Banks", url:"https://www.gherbertbanks.co.uk/",
    desc:"Herefordshire estate agents covering the Welsh Marches and rural Midlands. Periodic auction sales of residential, rural and agricultural property.",
    spec:"Residential", lots:["Residential Houses","Rural","Agricultural","Land"],
    conditions:["Refurbishment","Modern"], tenure:"Mostly Vacant",
    niches:["Herefordshire Property","Welsh Marches","Rural Residential"],
    reach:"Local", regions:["West Midlands","Herefordshire"], area:"Herefordshire & Welsh Marches",
    successRate:65, premium:"Low", bargains:"Moderate",
    vendors:["Private","Probate","Estate"], vendorPrimary:"Private & Probate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:2, historical:false, catalogue:false,
    highlights:["Strong Herefordshire local knowledge","Good rural and agricultural lots","Welsh Marches specialist"]
  },
  {
    id:55, name:"Goldings", url:"https://www.goldings.co.uk/",
    desc:"Hampshire-based estate agents with periodic property auction sales. Covers Basingstoke, Reading border and North Hampshire residential property market.",
    spec:"Residential", lots:["Residential Houses","Residential Flats"],
    conditions:["Modern","Refurbishment"], tenure:"Mostly Vacant",
    niches:["North Hampshire Property"],
    reach:"Local", regions:["South East","Hampshire"], area:"Basingstoke & North Hampshire",
    successRate:68, premium:"Moderate", bargains:"Moderate",
    vendors:["Private","Probate"], vendorPrimary:"Private & Probate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:2, historical:false, catalogue:false,
    highlights:["North Hampshire residential specialist","Good commuter belt property"]
  },
  {
    id:56, name:"Graham Watkins", url:"https://www.grahamwatkins.com/",
    desc:"South Wales auctioneers covering the Valleys and surrounding areas. Regular residential property auctions with competitive guide prices in affordable Welsh market areas.",
    spec:"Residential", lots:["Residential Houses","Residential Flats","Buy-to-Let"],
    conditions:["Refurbishment","Modern"], tenure:"Mixed",
    niches:["Welsh Valleys","Affordable Buy-to-Let"],
    reach:"Regional", regions:["Wales","South Wales","Valleys"], area:"South Wales Valleys",
    successRate:65, premium:"Low", bargains:"High",
    vendors:["Private","Probate","Lender"], vendorPrimary:"Private & Lender",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:2, historical:false, catalogue:true,
    highlights:["Good source of affordable Welsh Valleys stock","High yield buy-to-let potential","Competitive guide prices"]
  },
  {
    id:57, name:"Greenslade Taylor Hunt", url:"https://www.gth.net/",
    desc:"Major South West estate agents and auctioneers covering Somerset, Dorset and Devon. Regular property auctions with strong rural and residential mix.",
    spec:"Mixed", lots:["Residential Houses","Rural","Agricultural","Land","Commercial"],
    conditions:["Modern","Refurbishment","Development"], tenure:"Mixed",
    niches:["Somerset Property","Rural South West","Country Houses"],
    reach:"Regional", regions:["South West","Somerset","Dorset","Devon"], area:"Somerset, Dorset & Devon",
    successRate:70, premium:"Moderate", bargains:"Moderate",
    vendors:["Private","Probate","Estate","Corporate"], vendorPrimary:"Private & Estate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:3, historical:false, catalogue:true,
    highlights:["Leading South West regional auctioneer","Strong rural and agricultural expertise","Good Somerset and Dorset coverage"]
  },
  {
    id:58, name:"Gwilym Richards", url:"https://www.gwilymrichards.co.uk/",
    desc:"West Wales estate agents and auctioneers covering Carmarthen and Ceredigion. Residential and rural property auction sales in Welsh-speaking heartland.",
    spec:"Residential", lots:["Residential Houses","Rural","Land"],
    conditions:["Refurbishment","Modern"], tenure:"Mostly Vacant",
    niches:["West Wales Rural","Carmarthen Property"],
    reach:"Local", regions:["Wales","West Wales","Carmarthenshire"], area:"Carmarthen & West Wales",
    successRate:62, premium:"Low", bargains:"Moderate",
    vendors:["Private","Probate"], vendorPrimary:"Private & Probate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:1, historical:false, catalogue:false,
    highlights:["Deep West Wales local knowledge","Affordable rural residential lots"]
  },
  {
    id:59, name:"Hackney & Leigh", url:"https://www.hackneyandleigh.co.uk/",
    desc:"Lancashire and Lake District estate agents with periodic property auctions. Covers Lancaster, Kendal, Carnforth and the South Lakes with residential lots.",
    spec:"Residential", lots:["Residential Houses","Holiday Lets","Land"],
    conditions:["Modern","Refurbishment"], tenure:"Mostly Vacant",
    niches:["Lake District Property","Lancashire Country","Holiday Lets"],
    reach:"Regional", regions:["North West","Lancashire","Lake District","Cumbria"], area:"Lancaster & South Lakes",
    successRate:68, premium:"Moderate", bargains:"Moderate",
    vendors:["Private","Probate"], vendorPrimary:"Private & Probate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:2, historical:false, catalogue:true,
    highlights:["Lancaster and Lake District specialist","Good holiday let opportunities","Scenic property locations"]
  },
  {
    id:60, name:"Hair & Son", url:"https://www.hairandson.co.uk/",
    desc:"Essex auctioneers based in Southend-on-Sea. Regular property auction sales covering residential lots across Southend, Basildon, Thurrock and wider South Essex.",
    spec:"Residential", lots:["Residential Houses","Residential Flats","Buy-to-Let","Land"],
    conditions:["Refurbishment","Modern"], tenure:"Mixed",
    niches:["Essex Residential","Thames Gateway","Southend Property"],
    reach:"Regional", regions:["South East","Essex","Southend","Thames Gateway"], area:"Southend & South Essex",
    successRate:70, premium:"Moderate", bargains:"Moderate",
    vendors:["Private","Probate","Lender"], vendorPrimary:"Private & Probate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:3, historical:false, catalogue:true,
    highlights:["Strong South Essex auction presence","Good Thames Gateway opportunities","Regular auction calendar"]
  },
  {
    id:61, name:"Harman Healy", url:"https://www.harmanhealy.co.uk/",
    desc:"London and Surrey auctioneers specialising in commercial and residential investment property. Regular auctions featuring good quality investment lots.",
    spec:"Mixed", lots:["Commercial Investment","Residential","Mixed Use","Development Sites"],
    conditions:["Modern","Refurbishment","Development"], tenure:"Mixed",
    niches:["London Investment","Surrey Commercial","Mixed Use"],
    reach:"Regional", regions:["London","South East","Surrey"], area:"London & Surrey",
    successRate:72, premium:"High", bargains:"Low",
    vendors:["Corporate","Private","Lender"], vendorPrimary:"Corporate & Private",
    format:"Room", buyerPrem:"2% + VAT", deposit:"10%", completion:28,
    dataRating:3, historical:false, catalogue:true,
    highlights:["Good London and Surrey investment lots","Strong commercial auction practice","Regular auction calendar"]
  },
  {
    id:62, name:"Harry Ray & Company", url:"https://www.harryray.co.uk/",
    desc:"Cumbria-based estate agents covering Penrith, Carlisle and the Eden Valley. Periodic property auctions of residential and rural lots in the North Pennines and Lake District fringe.",
    spec:"Residential", lots:["Residential Houses","Rural","Agricultural","Land"],
    conditions:["Refurbishment","Modern"], tenure:"Mostly Vacant",
    niches:["Cumbria Property","Lake District Fringe","Rural North"],
    reach:"Local", regions:["North West","Cumbria","Lake District"], area:"Penrith & Eden Valley",
    successRate:62, premium:"Low", bargains:"Moderate",
    vendors:["Private","Probate"], vendorPrimary:"Private & Probate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:1, historical:false, catalogue:false,
    highlights:["Deep Cumbria and Eden Valley local knowledge","Affordable rural residential lots"]
  },
  {
    id:63, name:"Hawkesford", url:"https://www.hawkesford.co.uk/",
    desc:"Birmingham-based commercial property specialists with auction and private treaty sales. Handles offices, retail, industrial and investment property across the West Midlands.",
    spec:"Commercial", lots:["Commercial Investment","Office","Retail","Industrial","Development Sites"],
    conditions:["Modern","Refurbishment","Development"], tenure:"Mixed",
    niches:["Birmingham Commercial","Industrial Investment","Retail"],
    reach:"Regional", regions:["West Midlands","Birmingham"], area:"Birmingham & West Midlands",
    successRate:70, premium:"Moderate", bargains:"Moderate",
    vendors:["Corporate","Private","Lender"], vendorPrimary:"Corporate & Private",
    format:"Room", buyerPrem:"2% + VAT", deposit:"10%", completion:28,
    dataRating:3, historical:false, catalogue:true,
    highlights:["Birmingham commercial property specialist","Good office and industrial lots","Strong West Midlands market knowledge"]
  },
  {
    id:64, name:"Herbert R Thomas", url:"https://www.herbertthomas.co.uk/",
    desc:"South Wales auctioneers based in Neath. Regular residential property auctions covering Neath, Port Talbot, Swansea and the wider South Wales area.",
    spec:"Residential", lots:["Residential Houses","Residential Flats","Buy-to-Let"],
    conditions:["Refurbishment","Modern"], tenure:"Mixed",
    niches:["Neath Port Talbot","South Wales Residential"],
    reach:"Regional", regions:["Wales","South Wales","Neath","Swansea"], area:"Neath & Port Talbot",
    successRate:68, premium:"Low", bargains:"Moderate",
    vendors:["Private","Probate","Lender"], vendorPrimary:"Private & Probate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:2, historical:false, catalogue:true,
    highlights:["Strong Neath and Port Talbot coverage","Affordable residential stock","Good local market knowledge"]
  },
  {
    id:65, name:"Higgins Drysdale", url:"https://www.higginsdrysdale.co.uk/",
    desc:"South East property consultants with periodic auction sales. Covers Hampshire and surrounding Home Counties with residential and some commercial lots.",
    spec:"Residential", lots:["Residential Houses","Commercial","Land"],
    conditions:["Modern","Refurbishment"], tenure:"Mostly Vacant",
    niches:["Hampshire Residential","Home Counties"],
    reach:"Local", regions:["South East","Hampshire"], area:"Hampshire & Home Counties",
    successRate:65, premium:"Low", bargains:"Moderate",
    vendors:["Private","Probate"], vendorPrimary:"Private & Probate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:2, historical:false, catalogue:false,
    highlights:["Hampshire and Home Counties coverage","Residential focus"]
  },
  {
    id:66, name:"Hobbs Parker", url:"https://www.hobbsparker.co.uk/",
    desc:"Kent-based chartered surveyors and estate agents with regular property auctions. Strong rural, residential and land auction practice across Kent and East Sussex.",
    spec:"Mixed", lots:["Residential Houses","Rural","Agricultural","Land","Commercial","Development Sites"],
    conditions:["Modern","Refurbishment","Development"], tenure:"Mixed",
    niches:["Kent Rural","Agricultural Land","Hop Gardens","Barn Conversions"],
    reach:"Regional", regions:["South East","Kent","East Sussex"], area:"Kent & East Sussex",
    successRate:72, premium:"Moderate", bargains:"Moderate",
    vendors:["Private","Estate","Probate","Corporate"], vendorPrimary:"Private & Estate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:3, historical:false, catalogue:true,
    highlights:["Leading Kent and East Sussex auctioneer","Strong rural and agricultural expertise","Good land and development opportunities","Established chartered surveyor practice"]
  },
  {
    id:67, name:"Hollis & Morgan", url:"https://www.hollismorgan.co.uk/",
    desc:"Bristol-based property auctioneers with regular sales of residential and commercial lots. Good coverage of Bristol, Bath and surrounding North Somerset area.",
    spec:"Mixed", lots:["Residential Houses","Residential Flats","Commercial","Mixed Use"],
    conditions:["Modern","Refurbishment"], tenure:"Mixed",
    niches:["Bristol Property","Bath Property","Commercial Investment"],
    reach:"Regional", regions:["South West","Bristol","Bath","Somerset"], area:"Bristol & Bath",
    successRate:72, premium:"Moderate", bargains:"Moderate",
    vendors:["Private","Corporate","Probate"], vendorPrimary:"Private & Corporate",
    format:"Room", buyerPrem:"1% + VAT", deposit:"10%", completion:28,
    dataRating:3, historical:false, catalogue:true,
    highlights:["Strong Bristol and Bath auction presence","Good commercial and residential mix","Regular auction calendar"]
  },
  {
    id:68, name:"Howkins & Harrison", url:"https://www.howkinsandharrison.co.uk/",
    desc:"Warwickshire and East Midlands estate agents and surveyors with periodic property auctions. Covers Rugby, Lutterworth and surrounding areas with residential and rural lots.",
    spec:"Residential", lots:["Residential Houses","Rural","Land","Agricultural"],
    conditions:["Modern","Refurbishment"], tenure:"Mostly Vacant",
    niches:["Warwickshire Property","Rugby Area","Rural Midlands"],
    reach:"Regional", regions:["West Midlands","East Midlands","Warwickshire","Leicestershire"], area:"Warwickshire & East Midlands borders",
    successRate:68, premium:"Moderate", bargains:"Moderate",
    vendors:["Private","Probate","Estate"], vendorPrimary:"Private & Estate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:2, historical:false, catalogue:true,
    highlights:["Good Warwickshire and Leicestershire coverage","Residential and rural property mix"]
  },
  {
    id:69, name:"Humberts", url:"https://www.humberts.com/",
    desc:"Established national estate agents with periodic property auctions covering country houses, rural estates and residential property across the South and West of England.",
    spec:"Residential", lots:["Residential Houses","Rural","Country Houses","Land"],
    conditions:["Modern","Refurbishment"], tenure:"Mostly Vacant",
    niches:["Country Houses","Rural Estates","Period Property"],
    reach:"Regional", regions:["South West","South East","Hampshire","Dorset","Somerset"], area:"South & West England",
    successRate:70, premium:"Moderate", bargains:"Moderate",
    vendors:["Private","Estate"], vendorPrimary:"Private & Estate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:3, historical:false, catalogue:true,
    highlights:["Strong country house and rural estate expertise","Premium South and West England locations","Established brand"]
  },
  {
    id:70, name:"Hunters", url:"https://www.hunters.co.uk/",
    desc:"National estate agency franchise offering modern method of auction across the UK. Wide network of local branches providing auction services for residential property nationwide.",
    spec:"Residential", lots:["Residential Houses","Residential Flats","Buy-to-Let"],
    conditions:["Modern","Refurbishment"], tenure:"Mostly Vacant",
    niches:["Modern Method of Auction","National Residential"],
    reach:"National", regions:["National","North","Midlands","South"], area:"Nationwide via franchise network",
    successRate:72, premium:"Moderate", bargains:"Moderate",
    vendors:["Private","Probate"], vendorPrimary:"Private Vendors",
    format:"Online", buyerPrem:"Varies by branch", deposit:"10%", completion:56,
    dataRating:3, historical:false, catalogue:true,
    highlights:["National franchise auction network","Modern method of auction approach","Extended completion periods available","Wide geographic coverage"]
  },
  {
    id:71, name:"iam-sold", url:"https://www.iamsold.co.uk/",
    desc:"UK's largest modern method of auction provider, partnering with estate agents across the country. Specialises in conditional and unconditional online auction sales of residential property.",
    spec:"Residential", lots:["Residential Houses","Residential Flats","Buy-to-Let","Land"],
    conditions:["Modern","Refurbishment"], tenure:"Mostly Vacant",
    niches:["Modern Method of Auction","Online Platform","Conditional Auction"],
    reach:"National", regions:["National","England","Wales","Scotland"], area:"UK Nationwide",
    successRate:75, premium:"Low", bargains:"Moderate",
    vendors:["Private","Probate","Lender"], vendorPrimary:"Private Vendors",
    format:"Online", buyerPrem:"4.5% + VAT (reservation fee)", deposit:"Reservation fee", completion:56,
    dataRating:4, historical:true, catalogue:true,
    highlights:["UK's largest modern method of auction provider","Extended 56-day completion periods","Large volume of residential lots nationally","Online-first approach","Note: higher buyer fees than traditional auction"]
  },
  {
    id:72, name:"John Francis", url:"https://www.johnfrancis.co.uk/",
    desc:"West Wales estate agents with regular property auction sales covering Carmarthen, Aberystwyth, Haverfordwest and surrounding areas. Strong residential and rural coverage.",
    spec:"Residential", lots:["Residential Houses","Rural","Land","Agricultural"],
    conditions:["Refurbishment","Modern"], tenure:"Mostly Vacant",
    niches:["West Wales Property","Pembrokeshire","Ceredigion"],
    reach:"Regional", regions:["Wales","West Wales","Carmarthenshire","Pembrokeshire","Ceredigion"], area:"West Wales",
    successRate:68, premium:"Low", bargains:"Moderate",
    vendors:["Private","Probate","Estate"], vendorPrimary:"Private & Probate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:3, historical:false, catalogue:true,
    highlights:["Leading West Wales auctioneer","Good rural and coastal property","Strong Pembrokeshire coverage","Regular auction calendar"]
  },
  {
    id:73, name:"John Pye Auctions", url:"https://www.johnpyeproperty.co.uk/",
    desc:"National property auctioneer offering primarily online auction sales. Part of the wider John Pye auction group, handles residential, commercial and mixed-use properties nationwide.",
    spec:"Mixed", lots:["Residential Houses","Commercial","Mixed Use","Development Sites","Land"],
    conditions:["Refurbishment","Development","Modern"], tenure:"Mixed",
    niches:["Online Auction","Lender Sales","National Coverage"],
    reach:"National", regions:["National","Midlands","North","South"], area:"UK Nationwide",
    successRate:72, premium:"Moderate", bargains:"Moderate",
    vendors:["Lender","Corporate","Private","Developer"], vendorPrimary:"Lender & Corporate",
    format:"Online", buyerPrem:"2% + VAT", deposit:"10%", completion:28,
    dataRating:4, historical:true, catalogue:true,
    highlights:["National online property auction platform","Strong lender and corporate stock","Good data transparency and results","Part of major auction group","Wide variety of property types"]
  },
  {
    id:74, name:"Jones Peckover", url:"https://www.jonespeckover.co.uk/",
    desc:"North Wales estate agents and auctioneers covering Wrexham, Ruthin and surrounding areas. Handles residential, rural and agricultural property in the Welsh Marches.",
    spec:"Residential", lots:["Residential Houses","Rural","Agricultural","Land"],
    conditions:["Refurbishment","Modern"], tenure:"Mostly Vacant",
    niches:["North Wales Property","Welsh Marches","Rural"],
    reach:"Local", regions:["Wales","North Wales","Wrexham"], area:"Wrexham & North Wales",
    successRate:65, premium:"Low", bargains:"Moderate",
    vendors:["Private","Probate","Estate"], vendorPrimary:"Private & Probate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:2, historical:false, catalogue:false,
    highlights:["North Wales local specialist","Good rural and residential mix","Affordable lots"]
  },
  {
    id:75, name:"Kivells", url:"https://www.kivells.com/",
    desc:"Devon and Cornwall auctioneers with strong agricultural heritage. Regular property auctions covering residential, rural, agricultural and land across the South West peninsula.",
    spec:"Mixed", lots:["Residential Houses","Agricultural","Rural","Land","Development Sites"],
    conditions:["Modern","Refurbishment","Development"], tenure:"Mixed",
    niches:["Devon Farmland","Cornwall Property","Agricultural","Smallholdings"],
    reach:"Regional", regions:["South West","Devon","Cornwall"], area:"Devon & Cornwall",
    successRate:68, premium:"Moderate", bargains:"Moderate",
    vendors:["Private","Estate","Probate","Corporate"], vendorPrimary:"Private & Estate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:3, historical:false, catalogue:true,
    highlights:["Strong Devon and Cornwall agricultural heritage","Good farmland and rural property lots","Established South West auctioneer","Diverse lot types"]
  },
  {
    id:76, name:"Knight Frank", url:"https://auctions.knightfrank.com/",
    desc:"One of the world's premier property consultancies. Knight Frank's auction department handles premium commercial and residential investment properties nationally with exceptional data transparency.",
    spec:"Commercial", lots:["Commercial Investment","Residential Investment","Development Sites","Mixed Use","Ground Rents"],
    conditions:["Modern","Refurbishment","Development"], tenure:"Mixed",
    niches:["Premium Investment","Ground Rents","Institutional Grade","International"],
    reach:"National", regions:["London","National","South East","International"], area:"London, National & International",
    successRate:78, premium:"High", bargains:"Low",
    vendors:["Corporate","Institutional","Lender","Private"], vendorPrimary:"Corporate & Institutional",
    format:"Hybrid", buyerPrem:"2% + VAT", deposit:"10%", completion:20,
    dataRating:5, historical:true, catalogue:true,
    highlights:["World-class property consultancy","Premium investment-grade lots","Excellent data transparency and results archive","Strong institutional and corporate vendor base","National and international reach"]
  },
  {
    id:77, name:"Lambert & Foster", url:"https://www.lambertandfoster.co.uk/",
    desc:"Kent-based chartered surveyors and estate agents with regular property auctions. Covers the Garden of England with residential, rural and land lots.",
    spec:"Residential", lots:["Residential Houses","Rural","Land","Agricultural"],
    conditions:["Modern","Refurbishment"], tenure:"Mostly Vacant",
    niches:["Kent Property","Garden of England","Rural Residential"],
    reach:"Regional", regions:["South East","Kent"], area:"Kent",
    successRate:68, premium:"Moderate", bargains:"Moderate",
    vendors:["Private","Probate","Estate"], vendorPrimary:"Private & Probate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:3, historical:false, catalogue:true,
    highlights:["Good Kent and Garden of England coverage","Established chartered surveyor practice","Rural and residential mix"]
  },
  {
    id:78, name:"Lambert Smith Hampton", url:"https://www.lsh.co.uk/",
    desc:"Major national commercial property consultancy with dedicated auction department. Specialists in commercial investment, development and strategic property disposals across the UK.",
    spec:"Commercial", lots:["Commercial Investment","Office","Retail","Industrial","Development Sites","Mixed Use"],
    conditions:["Modern","Refurbishment","Development"], tenure:"Mixed",
    niches:["Institutional Commercial","Corporate Disposals","Industrial Investment","Strategic Sites"],
    reach:"National", regions:["London","National","Midlands","North","South"], area:"UK Nationwide",
    successRate:75, premium:"Moderate", bargains:"Moderate",
    vendors:["Corporate","Institutional","Lender","Developer"], vendorPrimary:"Corporate & Institutional",
    format:"Room", buyerPrem:"2% + VAT", deposit:"10%", completion:20,
    dataRating:4, historical:true, catalogue:true,
    highlights:["Major national commercial auctioneer","Strong institutional and corporate stock","Excellent for commercial investment","Good data and results transparency"]
  },
  {
    id:79, name:"Landwood Property Auctions", url:"https://www.landwoodproperty.co.uk/",
    desc:"Manchester-based commercial and residential property auctioneers. Covers the North West with regular auction sales of investment, development and mixed-use property.",
    spec:"Mixed", lots:["Commercial Investment","Residential","Development Sites","Mixed Use","Land"],
    conditions:["Modern","Refurbishment","Development"], tenure:"Mixed",
    niches:["Manchester Commercial","North West Development","Industrial"],
    reach:"Regional", regions:["North West","Manchester","Lancashire"], area:"Manchester & North West",
    successRate:72, premium:"Moderate", bargains:"Moderate",
    vendors:["Corporate","Lender","Private","Developer"], vendorPrimary:"Corporate & Lender",
    format:"Hybrid", buyerPrem:"2% + VAT", deposit:"10%", completion:28,
    dataRating:3, historical:false, catalogue:true,
    highlights:["Good Manchester commercial auction practice","Strong North West coverage","Development and investment lots"]
  },
  {
    id:80, name:"Leonards", url:"https://www.leonards.co.uk/",
    desc:"Property auctioneers offering residential lots. Regular auction sales covering local residential property with a mix of investment and owner-occupier opportunities.",
    spec:"Residential", lots:["Residential Houses","Residential Flats","Buy-to-Let"],
    conditions:["Modern","Refurbishment"], tenure:"Mostly Vacant",
    niches:["Residential Resale"],
    reach:"Regional", regions:["South East"], area:"South East England",
    successRate:65, premium:"Low", bargains:"Moderate",
    vendors:["Private","Probate"], vendorPrimary:"Private & Probate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:2, historical:false, catalogue:false,
    highlights:["Local residential auction practice"]
  },
  {
    id:81, name:"Lextons", url:"https://www.lextons.com/",
    desc:"Brighton and Hove estate agents offering property auction services. Residential property auctions in the Brighton and South Coast area with premium coastal lots.",
    spec:"Residential", lots:["Residential Flats","Residential Houses"],
    conditions:["Modern","Refurbishment"], tenure:"Mostly Vacant",
    niches:["Brighton Property","South Coast Premium","Seaside Residential"],
    reach:"Regional", regions:["South East","Sussex","Brighton"], area:"Brighton & Hove",
    successRate:70, premium:"High", bargains:"Low",
    vendors:["Private","Probate"], vendorPrimary:"Private Vendors",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:2, historical:false, catalogue:true,
    highlights:["Brighton and Hove specialist","Premium seaside location","Strong local market knowledge"]
  },
  {
    id:82, name:"Lodge & Thomas", url:"https://www.lodgeandthomas.co.uk/",
    desc:"Shropshire-based estate agents covering Church Stretton and the South Shropshire Hills. Periodic auction sales of residential and rural property in picturesque countryside.",
    spec:"Residential", lots:["Residential Houses","Rural","Land"],
    conditions:["Modern","Refurbishment"], tenure:"Mostly Vacant",
    niches:["Shropshire Hills","Rural Residential","Period Cottages"],
    reach:"Local", regions:["West Midlands","Shropshire"], area:"Church Stretton & South Shropshire",
    successRate:62, premium:"Low", bargains:"Moderate",
    vendors:["Private","Probate"], vendorPrimary:"Private & Probate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:1, historical:false, catalogue:false,
    highlights:["South Shropshire and Stretton Hills specialist","Picturesque rural property opportunities"]
  },
  {
    id:83, name:"Loveitts", url:"https://www.loveitts.co.uk/",
    desc:"Coventry and West Midlands auctioneers with regular property auctions. Good coverage of residential and commercial lots across Coventry, Warwickshire and wider Midlands area.",
    spec:"Mixed", lots:["Residential Houses","Commercial","Development Sites","Land","Buy-to-Let"],
    conditions:["Modern","Refurbishment","Development"], tenure:"Mixed",
    niches:["Coventry Property","West Midlands Residential","Development Sites"],
    reach:"Regional", regions:["West Midlands","Coventry","Warwickshire"], area:"Coventry & Warwickshire",
    successRate:70, premium:"Moderate", bargains:"Moderate",
    vendors:["Private","Lender","Probate","Corporate"], vendorPrimary:"Private & Lender",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:3, historical:false, catalogue:true,
    highlights:["Strong Coventry and Warwickshire auction presence","Good residential and commercial mix","Regular auction calendar"]
  },
  {
    id:84, name:"Luscombe Maye", url:"https://www.luscombemaye.co.uk/",
    desc:"South Devon estate agents covering Totnes, Kingsbridge and the South Hams. Periodic property auctions of residential and rural lots in one of Devon's most desirable areas.",
    spec:"Residential", lots:["Residential Houses","Rural","Holiday Lets","Land"],
    conditions:["Modern","Refurbishment"], tenure:"Mostly Vacant",
    niches:["South Devon","South Hams","Holiday Lets","Coastal Property"],
    reach:"Regional", regions:["South West","Devon","South Hams"], area:"South Devon & South Hams",
    successRate:68, premium:"Moderate", bargains:"Moderate",
    vendors:["Private","Probate"], vendorPrimary:"Private & Probate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:2, historical:false, catalogue:true,
    highlights:["South Devon and South Hams specialist","Holiday let and coastal opportunities","Desirable location property"]
  },
  {
    id:85, name:"Maggs & Allen", url:"https://www.maggsandallen.co.uk/",
    desc:"Bristol-based property auctioneers established in 1858. Regular auction sales of residential, commercial and mixed-use property across Bristol and surrounding areas.",
    spec:"Mixed", lots:["Residential Houses","Commercial","Mixed Use","Development Sites"],
    conditions:["Modern","Refurbishment","Development"], tenure:"Mixed",
    niches:["Bristol Property","Commercial Investment","City Centre"],
    reach:"Regional", regions:["South West","Bristol","Somerset"], area:"Bristol & North Somerset",
    successRate:72, premium:"Moderate", bargains:"Moderate",
    vendors:["Private","Corporate","Probate","Lender"], vendorPrimary:"Private & Corporate",
    format:"Room", buyerPrem:"1.5% + VAT", deposit:"10%", completion:28,
    dataRating:3, historical:false, catalogue:true,
    highlights:["Established Bristol auctioneer since 1858","Good commercial and residential mix","Strong Bristol market knowledge","Regular auction calendar"]
  },
  {
    id:86, name:"Main & Main", url:"https://www.mainandmain.co.uk/",
    desc:"North West property auctioneers covering Greater Manchester and Lancashire. Residential property auction sales with affordable stock suitable for investors.",
    spec:"Residential", lots:["Residential Houses","Residential Flats","Buy-to-Let"],
    conditions:["Refurbishment","Modern"], tenure:"Mixed",
    niches:["Manchester Residential","North West Buy-to-Let"],
    reach:"Regional", regions:["North West","Manchester","Lancashire"], area:"Manchester & Lancashire",
    successRate:65, premium:"Low", bargains:"Moderate",
    vendors:["Private","Probate","Lender"], vendorPrimary:"Private & Probate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:2, historical:false, catalogue:false,
    highlights:["Manchester and Lancashire residential focus","Affordable investment stock"]
  },
  {
    id:87, name:"Mark Jenkinson & Son", url:"https://www.markjenkinson.co.uk/",
    desc:"Sheffield-based auctioneers with regular property auction sales. Covers South Yorkshire and the wider Sheffield area with residential, commercial and mixed lots.",
    spec:"Mixed", lots:["Residential Houses","Commercial","Development Sites","Buy-to-Let","Land"],
    conditions:["Modern","Refurbishment","Development"], tenure:"Mixed",
    niches:["Sheffield Property","South Yorkshire Investment","Development"],
    reach:"Regional", regions:["Yorkshire","South Yorkshire","Sheffield"], area:"Sheffield & South Yorkshire",
    successRate:70, premium:"Low", bargains:"Moderate",
    vendors:["Private","Lender","Probate","Corporate"], vendorPrimary:"Private & Lender",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:3, historical:false, catalogue:true,
    highlights:["Strong Sheffield and South Yorkshire presence","Good mix of residential and commercial","Regular auction calendar","Affordable investment opportunities"]
  },
  {
    id:88, name:"Martin & Pole", url:"https://www.martinandpole.co.uk/",
    desc:"London and South East property auctioneers. Periodic auction sales covering residential lots across London and the Home Counties.",
    spec:"Residential", lots:["Residential Houses","Residential Flats","Land"],
    conditions:["Modern","Refurbishment"], tenure:"Mostly Vacant",
    niches:["London Residential","Home Counties"],
    reach:"Regional", regions:["London","South East"], area:"London & Home Counties",
    successRate:68, premium:"Moderate", bargains:"Moderate",
    vendors:["Private","Probate"], vendorPrimary:"Private & Probate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:2, historical:false, catalogue:true,
    highlights:["London and Home Counties residential lots"]
  },
  {
    id:89, name:"McCartneys", url:"https://www.mccartneys.co.uk/",
    desc:"Mid Wales and Shropshire estate agents and auctioneers. Strong rural, agricultural and residential auction practice covering Ludlow, Knighton, Builth Wells and the Welsh Marches.",
    spec:"Mixed", lots:["Residential Houses","Agricultural","Rural","Land","Development Sites"],
    conditions:["Modern","Refurbishment","Development"], tenure:"Mixed",
    niches:["Welsh Marches","Agricultural Land","Smallholdings","Hill Farms"],
    reach:"Regional", regions:["Wales","Mid Wales","Shropshire","West Midlands"], area:"Mid Wales & Welsh Marches",
    successRate:68, premium:"Low", bargains:"Moderate",
    vendors:["Private","Probate","Estate"], vendorPrimary:"Private & Estate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:3, historical:false, catalogue:true,
    highlights:["Leading Mid Wales and Marches auctioneer","Strong agricultural and rural expertise","Good land and smallholding opportunities","Regular auction calendar"]
  },
  {
    id:90, name:"McHugh & Co", url:"https://www.mchughandco.com/",
    desc:"London property auctioneers specialising in residential and commercial lots. Regular auction sales with good mix of investment property across Greater London and the South East.",
    spec:"Mixed", lots:["Residential Houses","Residential Flats","Commercial","Mixed Use","Development Sites"],
    conditions:["Modern","Refurbishment","Development"], tenure:"Mixed",
    niches:["London Investment","Commercial Mixed-Use","Development Opportunities"],
    reach:"Regional", regions:["London","South East","Greater London"], area:"London & South East",
    successRate:72, premium:"High", bargains:"Low",
    vendors:["Private","Lender","Corporate","Probate"], vendorPrimary:"Private & Lender",
    format:"Room", buyerPrem:"2% + VAT", deposit:"10%", completion:28,
    dataRating:3, historical:false, catalogue:true,
    highlights:["Good London auction presence","Regular sales calendar","Mixed residential and commercial lots","Investment-focused offering"]
  },
  {
    id:91, name:"Meller Braggins", url:"https://www.mellerbraggins.co.uk/",
    desc:"Cheshire estate agents based in Knutsford and Northwich. Periodic property auctions covering residential lots across Cheshire and south Manchester borders.",
    spec:"Residential", lots:["Residential Houses","Residential Flats","Land"],
    conditions:["Modern","Refurbishment"], tenure:"Mostly Vacant",
    niches:["Cheshire Residential","Knutsford Property"],
    reach:"Regional", regions:["North West","Cheshire","South Manchester"], area:"Knutsford & Cheshire",
    successRate:68, premium:"Moderate", bargains:"Moderate",
    vendors:["Private","Probate"], vendorPrimary:"Private & Probate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:3, historical:false, catalogue:true,
    highlights:["Good Cheshire residential market knowledge","Established Knutsford practice"]
  },
  {
    id:92, name:"Michael Poole", url:"https://www.michaelpoole.co.uk/",
    desc:"Teesside-based estate agents covering Middlesbrough, Stockton and the wider Tees Valley. Periodic property auctions of residential lots at competitive North East prices.",
    spec:"Residential", lots:["Residential Houses","Residential Flats","Buy-to-Let"],
    conditions:["Refurbishment","Modern"], tenure:"Mixed",
    niches:["Teesside Property","North East Buy-to-Let","Affordable Housing"],
    reach:"Regional", regions:["North East","Teesside","Middlesbrough"], area:"Teesside & Tees Valley",
    successRate:65, premium:"Low", bargains:"High",
    vendors:["Private","Probate","Lender"], vendorPrimary:"Private & Probate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:2, historical:false, catalogue:true,
    highlights:["Strong Teesside local presence","Very affordable residential stock","Good buy-to-let yield potential"]
  },
  {
    id:93, name:"Morgan Beddoe", url:"https://www.morganbeddoe.co.uk/",
    desc:"South Wales estate agents covering Pontypool, Cwmbran and the Eastern Valleys. Periodic residential property auctions in the Torfaen and Monmouthshire areas.",
    spec:"Residential", lots:["Residential Houses","Residential Flats"],
    conditions:["Refurbishment","Modern"], tenure:"Mostly Vacant",
    niches:["Eastern Valleys","Torfaen Property"],
    reach:"Local", regions:["Wales","South Wales","Monmouthshire"], area:"Pontypool & Eastern Valleys",
    successRate:65, premium:"Low", bargains:"Moderate",
    vendors:["Private","Probate"], vendorPrimary:"Private & Probate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:2, historical:false, catalogue:false,
    highlights:["Eastern Valleys and Torfaen specialist","Affordable residential lots"]
  },
  {
    id:94, name:"Morris Marshall & Poole", url:"https://www.mmp.co.uk/",
    desc:"Mid Wales estate agents with regular auction sales covering Newtown, Welshpool, Aberystwyth and surrounding areas. Strong residential and rural property auction practice.",
    spec:"Residential", lots:["Residential Houses","Rural","Agricultural","Land"],
    conditions:["Refurbishment","Modern"], tenure:"Mostly Vacant",
    niches:["Mid Wales Property","Rural Wales","Smallholdings"],
    reach:"Regional", regions:["Wales","Mid Wales","Powys","Ceredigion"], area:"Mid Wales",
    successRate:65, premium:"Low", bargains:"Moderate",
    vendors:["Private","Probate","Estate"], vendorPrimary:"Private & Probate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:2, historical:false, catalogue:true,
    highlights:["Strong Mid Wales coverage","Good rural and agricultural lots","Affordable Welsh residential stock"]
  },
  {
    id:95, name:"Nesbits", url:"https://www.nesbits.co.uk/",
    desc:"Hampshire-based estate agents covering Portsmouth, Southsea, Fareham and the wider South Coast. Periodic property auctions of residential lots.",
    spec:"Residential", lots:["Residential Houses","Residential Flats","Buy-to-Let"],
    conditions:["Modern","Refurbishment"], tenure:"Mostly Vacant",
    niches:["Portsmouth Property","South Coast Residential"],
    reach:"Regional", regions:["South East","Hampshire","Portsmouth"], area:"Portsmouth & South Hampshire",
    successRate:68, premium:"Moderate", bargains:"Moderate",
    vendors:["Private","Probate"], vendorPrimary:"Private & Probate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:2, historical:false, catalogue:true,
    highlights:["Strong Portsmouth and South Hampshire coverage","Good residential auction lots"]
  },
  {
    id:96, name:"Network Auctions", url:"https://www.networkauctions.com/",
    desc:"National property auctioneer with regular high-quality sales of residential and commercial lots. Well-regarded for transparent processes and good data availability across England and Wales.",
    spec:"Mixed", lots:["Residential Houses","Commercial","Mixed Use","Development Sites","Land","Buy-to-Let"],
    conditions:["Modern","Refurbishment","Development"], tenure:"Mixed",
    niches:["National Investment","Development Opportunities","Mixed Use"],
    reach:"National", regions:["London","National","South East","Midlands","North"], area:"England & Wales",
    successRate:75, premium:"Moderate", bargains:"Moderate",
    vendors:["Lender","Private","Corporate","Probate"], vendorPrimary:"Lender & Private",
    format:"Hybrid", buyerPrem:"2% + VAT", deposit:"10%", completion:20,
    dataRating:4, historical:true, catalogue:true,
    highlights:["Respected national auctioneer","Good data transparency and results","Regular auction calendar","Strong mix of residential and commercial","Well-regarded in the investment community"]
  },
  {
    id:97, name:"Nicholas James Property", url:"https://www.nicholasjames.co.uk/",
    desc:"South West property auctioneers covering residential lots across Devon, Somerset and surrounding areas. Regular auctions of residential investment and owner-occupier properties.",
    spec:"Residential", lots:["Residential Houses","Residential Flats","Buy-to-Let"],
    conditions:["Modern","Refurbishment"], tenure:"Mostly Vacant",
    niches:["South West Residential"],
    reach:"Regional", regions:["South West","Devon","Somerset"], area:"South West England",
    successRate:65, premium:"Low", bargains:"Moderate",
    vendors:["Private","Probate"], vendorPrimary:"Private & Probate",
    format:"Room", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:2, historical:false, catalogue:true,
    highlights:["South West residential focus","Good selection of lots in Devon and Somerset"]
  },
  {
    id:98, name:"Online Property Auctions Scotland", url:"https://www.opas.co.uk/",
    desc:"Scotland-focused online property auction platform. Offers residential and commercial lots across Scotland with a fully online bidding process designed for the Scottish market.",
    spec:"Residential", lots:["Residential Houses","Residential Flats","Commercial","Land"],
    conditions:["Modern","Refurbishment"], tenure:"Mixed",
    niches:["Scottish Property","Online Scottish Auction","Edinburgh","Glasgow"],
    reach:"Regional", regions:["Scotland","Edinburgh","Glasgow","Highlands"], area:"Scotland-wide",
    successRate:68, premium:"Moderate", bargains:"Moderate",
    vendors:["Private","Lender","Probate"], vendorPrimary:"Private & Lender",
    format:"Online", buyerPrem:"3% + VAT", deposit:"10%", completion:28,
    dataRating:3, historical:false, catalogue:true,
    highlights:["Scotland-focused online auction platform","Good coverage across Scotland","Fully online bidding process","Residential and commercial lots"]
  },
  {
    id:99, name:"Open Door Property", url:"https://www.opendoorpropertyltd.co.uk/",
    desc:"Modern method of auction provider offering residential property sales. Online auction platform with extended completion timescales for residential property across England.",
    spec:"Residential", lots:["Residential Houses","Residential Flats"],
    conditions:["Modern","Refurbishment"], tenure:"Mostly Vacant",
    niches:["Modern Method of Auction","Online Residential"],
    reach:"Regional", regions:["Midlands","North"], area:"Midlands & North",
    successRate:65, premium:"Low", bargains:"Moderate",
    vendors:["Private","Probate"], vendorPrimary:"Private Vendors",
    format:"Online", buyerPrem:"Reservation fee applies", deposit:"Reservation fee", completion:56,
    dataRating:2, historical:false, catalogue:false,
    highlights:["Modern method of auction approach","Extended completion periods","Online bidding platform"]
  },
  {
    id:100, name:"Pattinson", url:"https://www.pattinson.co.uk/auction",
    desc:"Leading North East estate agents with a strong property auction division. Regular high-volume auction sales of residential properties across Newcastle, Sunderland, Durham and the wider North East.",
    spec:"Residential", lots:["Residential Houses","Residential Flats","Buy-to-Let","HMO","Land"],
    conditions:["Modern","Refurbishment","Development"], tenure:"Mixed",
    niches:["North East Residential","Newcastle Property","Buy-to-Let","Student HMO"],
    reach:"Regional", regions:["North East","Newcastle","Sunderland","Durham","Northumberland"], area:"Newcastle & North East England",
    successRate:75, premium:"Moderate", bargains:"Moderate",
    vendors:["Private","Lender","Probate","Corporate"], vendorPrimary:"Private & Lender",
    format:"Hybrid", buyerPrem:"0%", deposit:"10%", completion:28,
    dataRating:4, historical:true, catalogue:true,
    highlights:["Leading North East property auctioneer","Excellent success rates","Strong residential and buy-to-let stock","Good data transparency with results published","Regular high-volume auction calendar","No buyer's premium"]
  }
];
