<?php

namespace Database\Seeders;

use App\Models\Lot;
use Illuminate\Database\Seeder;

class LotSeeder extends Seeder
{
    public function run(): void
    {
        $lots = [
            // --- Allsop (house_id: 5) ---
            [
                'auction_house_id' => 5,
                'title' => '3-Bed Semi-Detached House - Refurbishment Opportunity',
                'address' => '14 Maple Avenue, Croydon',
                'postcode' => 'CR0 6TN',
                'region' => 'London',
                'property_type' => 'residential',
                'lot_condition' => 'refurbishment',
                'bedrooms' => 3,
                'guide_price_low' => 280000,
                'guide_price_high' => 310000,
                'auction_date' => '2026-03-12',
                'lot_number' => 15,
                'status' => 'upcoming',
                'external_url' => 'https://www.allsop.co.uk/lot/example-1',
            ],
            [
                'auction_house_id' => 5,
                'title' => 'Ground Floor Commercial Unit with A1/A2 Use',
                'address' => '221 High Street, Bromley',
                'postcode' => 'BR1 1NG',
                'region' => 'London',
                'property_type' => 'commercial',
                'lot_condition' => 'modern',
                'bedrooms' => null,
                'guide_price_low' => 175000,
                'guide_price_high' => 200000,
                'auction_date' => '2026-03-12',
                'lot_number' => 22,
                'status' => 'upcoming',
                'external_url' => 'https://www.allsop.co.uk/lot/example-2',
            ],
            [
                'auction_house_id' => 5,
                'title' => 'Freehold Vacant 4-Bed Detached with Large Garden',
                'address' => '8 Oak Lane, Enfield',
                'postcode' => 'EN1 3JP',
                'region' => 'London',
                'property_type' => 'residential',
                'lot_condition' => 'refurbishment',
                'bedrooms' => 4,
                'guide_price_low' => 425000,
                'guide_price_high' => 475000,
                'auction_date' => '2026-04-23',
                'lot_number' => 8,
                'status' => 'upcoming',
                'external_url' => 'https://www.allsop.co.uk/lot/example-3',
            ],

            // --- Auction House UK (house_id: 13) ---
            [
                'auction_house_id' => 13,
                'title' => '2-Bed Terrace House - Ideal BTL Investment',
                'address' => '27 Stanley Street, Burnley',
                'postcode' => 'BB11 4HE',
                'region' => 'North West',
                'property_type' => 'residential',
                'lot_condition' => 'modern',
                'bedrooms' => 2,
                'guide_price_low' => 45000,
                'guide_price_high' => 55000,
                'auction_date' => '2026-03-05',
                'lot_number' => 3,
                'status' => 'upcoming',
            ],
            [
                'auction_house_id' => 13,
                'title' => 'Former Public House with Planning for 6 Flats',
                'address' => '1 Market Place, Barnsley',
                'postcode' => 'S70 1SN',
                'region' => 'Yorkshire',
                'property_type' => 'mixed',
                'lot_condition' => 'development',
                'bedrooms' => null,
                'guide_price_low' => 120000,
                'guide_price_high' => 150000,
                'auction_date' => '2026-03-05',
                'lot_number' => 18,
                'status' => 'upcoming',
            ],

            // --- Bond Wolfe (house_id: 19) ---
            [
                'auction_house_id' => 19,
                'title' => '3-Bed End Terrace - Tenanted Producing £7,200 PA',
                'address' => '45 Birchfield Road, Birmingham',
                'postcode' => 'B20 3DG',
                'region' => 'West Midlands',
                'property_type' => 'residential',
                'lot_condition' => 'modern',
                'bedrooms' => 3,
                'guide_price_low' => 85000,
                'guide_price_high' => 95000,
                'auction_date' => '2026-03-19',
                'lot_number' => 12,
                'status' => 'upcoming',
            ],
            [
                'auction_house_id' => 19,
                'title' => 'Lock-Up Garage and Land with Development Potential',
                'address' => 'Rear of 112 High Street, Smethwick',
                'postcode' => 'B66 1LH',
                'region' => 'West Midlands',
                'property_type' => 'land',
                'lot_condition' => 'development',
                'bedrooms' => null,
                'guide_price_low' => 20000,
                'guide_price_high' => 30000,
                'auction_date' => '2026-03-19',
                'lot_number' => 45,
                'status' => 'upcoming',
            ],
            [
                'auction_house_id' => 19,
                'title' => 'Vacant 2-Bed Flat Above Shops - Refurb Required',
                'address' => '89A Soho Road, Handsworth',
                'postcode' => 'B21 9SP',
                'region' => 'West Midlands',
                'property_type' => 'residential',
                'lot_condition' => 'refurbishment',
                'bedrooms' => 2,
                'guide_price_low' => 48000,
                'guide_price_high' => 58000,
                'auction_date' => '2026-04-16',
                'lot_number' => 7,
                'status' => 'upcoming',
            ],

            // --- Clive Emson (house_id: 36) ---
            [
                'auction_house_id' => 36,
                'title' => 'Freehold Building Plot with Planning Permission',
                'address' => 'Land adj 5 The Green, Ashford',
                'postcode' => 'TN24 8RX',
                'region' => 'South East',
                'property_type' => 'land',
                'lot_condition' => 'development',
                'bedrooms' => null,
                'guide_price_low' => 90000,
                'guide_price_high' => 110000,
                'auction_date' => '2026-03-25',
                'lot_number' => 4,
                'status' => 'upcoming',
            ],
            [
                'auction_house_id' => 36,
                'title' => '1-Bed Retirement Flat - Vacant Possession',
                'address' => '12 Sea View Court, Folkestone',
                'postcode' => 'CT20 2PR',
                'region' => 'South East',
                'property_type' => 'residential',
                'lot_condition' => 'modern',
                'bedrooms' => 1,
                'guide_price_low' => 55000,
                'guide_price_high' => 65000,
                'auction_date' => '2026-03-25',
                'lot_number' => 11,
                'status' => 'upcoming',
            ],

            // --- Cottons (house_id: 38) ---
            [
                'auction_house_id' => 38,
                'title' => 'Portfolio of 3 Tenanted Terraces - 8.5% Yield',
                'address' => '15, 17 & 19 Chapel Street, Coventry',
                'postcode' => 'CV1 4GR',
                'region' => 'West Midlands',
                'property_type' => 'residential',
                'lot_condition' => 'modern',
                'bedrooms' => 2,
                'guide_price_low' => 195000,
                'guide_price_high' => 225000,
                'auction_date' => '2026-03-27',
                'lot_number' => 1,
                'status' => 'upcoming',
            ],

            // --- Barnett Ross (house_id: 16) ---
            [
                'auction_house_id' => 16,
                'title' => '1-Bed Flat in Period Conversion - NW London',
                'address' => '3A Finchley Road, Hampstead',
                'postcode' => 'NW3 6ET',
                'region' => 'London',
                'property_type' => 'residential',
                'lot_condition' => 'refurbishment',
                'bedrooms' => 1,
                'guide_price_low' => 225000,
                'guide_price_high' => 275000,
                'auction_date' => '2026-03-10',
                'lot_number' => 6,
                'status' => 'upcoming',
            ],

            // --- Network Auctions (house_id: 96) ---
            [
                'auction_house_id' => 96,
                'title' => 'Mixed-Use Freehold - Shop with 2-Bed Flat Above',
                'address' => '48 Station Road, Harrow',
                'postcode' => 'HA1 2SQ',
                'region' => 'London',
                'property_type' => 'mixed',
                'lot_condition' => 'modern',
                'bedrooms' => 2,
                'guide_price_low' => 320000,
                'guide_price_high' => 360000,
                'auction_date' => '2026-03-14',
                'lot_number' => 9,
                'status' => 'upcoming',
            ],

            // --- Knight Frank (house_id: 76) ---
            [
                'auction_house_id' => 76,
                'title' => 'Prime Freehold Office Investment - City of London',
                'address' => '15 Eastcheap, London',
                'postcode' => 'EC3M 1BU',
                'region' => 'London',
                'property_type' => 'commercial',
                'lot_condition' => 'modern',
                'bedrooms' => null,
                'guide_price_low' => 1250000,
                'guide_price_high' => 1500000,
                'auction_date' => '2026-04-02',
                'lot_number' => 2,
                'status' => 'upcoming',
            ],
            [
                'auction_house_id' => 76,
                'title' => 'Residential Development Site - 0.5 Acres - PP for 8 Units',
                'address' => 'Land at Church Lane, Guildford',
                'postcode' => 'GU1 3RJ',
                'region' => 'South East',
                'property_type' => 'land',
                'lot_condition' => 'development',
                'bedrooms' => null,
                'guide_price_low' => 800000,
                'guide_price_high' => 950000,
                'auction_date' => '2026-04-02',
                'lot_number' => 5,
                'status' => 'upcoming',
            ],

            // --- Pattinson (house_id: 100) ---
            [
                'auction_house_id' => 100,
                'title' => '2-Bed Flat - Probate Sale - Quick Completion',
                'address' => '14 Westgate Road, Newcastle',
                'postcode' => 'NE1 1TT',
                'region' => 'North East',
                'property_type' => 'residential',
                'lot_condition' => 'refurbishment',
                'bedrooms' => 2,
                'guide_price_low' => 65000,
                'guide_price_high' => 75000,
                'auction_date' => '2026-03-06',
                'lot_number' => 21,
                'status' => 'upcoming',
            ],
            [
                'auction_house_id' => 100,
                'title' => '3-Bed Semi - Repossession - Sunderland',
                'address' => '38 Park Lane, Sunderland',
                'postcode' => 'SR2 7NB',
                'region' => 'North East',
                'property_type' => 'residential',
                'lot_condition' => 'refurbishment',
                'bedrooms' => 3,
                'guide_price_low' => 55000,
                'guide_price_high' => 70000,
                'auction_date' => '2026-03-06',
                'lot_number' => 34,
                'status' => 'upcoming',
            ],

            // --- Edward Mellor (house_id: 46) ---
            [
                'auction_house_id' => 46,
                'title' => '4-Bed Detached Requiring Full Renovation',
                'address' => '7 Buxton Road, Stockport',
                'postcode' => 'SK2 6NB',
                'region' => 'North West',
                'property_type' => 'residential',
                'lot_condition' => 'refurbishment',
                'bedrooms' => 4,
                'guide_price_low' => 180000,
                'guide_price_high' => 220000,
                'auction_date' => '2026-03-18',
                'lot_number' => 6,
                'status' => 'upcoming',
            ],
            [
                'auction_house_id' => 46,
                'title' => 'Commercial Premises - Former Hair Salon',
                'address' => '29 Market Street, Hyde',
                'postcode' => 'SK14 2AD',
                'region' => 'North West',
                'property_type' => 'commercial',
                'lot_condition' => 'refurbishment',
                'bedrooms' => null,
                'guide_price_low' => 35000,
                'guide_price_high' => 45000,
                'auction_date' => '2026-03-18',
                'lot_number' => 28,
                'status' => 'upcoming',
            ],

            // --- iam-sold (house_id: 71) ---
            [
                'auction_house_id' => 71,
                'title' => '2-Bed Bungalow - Ideal First-Time Investor Property',
                'address' => '5 Rose Crescent, Cardiff',
                'postcode' => 'CF14 3QR',
                'region' => 'Wales',
                'property_type' => 'residential',
                'lot_condition' => 'modern',
                'bedrooms' => 2,
                'guide_price_low' => 130000,
                'guide_price_high' => 150000,
                'auction_date' => '2026-03-20',
                'lot_number' => 14,
                'status' => 'upcoming',
            ],
            [
                'auction_house_id' => 71,
                'title' => '3-Bed Terrace - Swansea - Tenanted at £600pcm',
                'address' => '44 High Street, Swansea',
                'postcode' => 'SA1 1LE',
                'region' => 'Wales',
                'property_type' => 'residential',
                'lot_condition' => 'modern',
                'bedrooms' => 3,
                'guide_price_low' => 88000,
                'guide_price_high' => 100000,
                'auction_date' => '2026-04-08',
                'lot_number' => 5,
                'status' => 'upcoming',
            ],

            // --- Auction Estates (house_id: 12) ---
            [
                'auction_house_id' => 12,
                'title' => '2-Bed Mid-Terrace - Nottingham City Centre',
                'address' => '63 Radford Boulevard, Nottingham',
                'postcode' => 'NG7 5FS',
                'region' => 'East Midlands',
                'property_type' => 'residential',
                'lot_condition' => 'refurbishment',
                'bedrooms' => 2,
                'guide_price_low' => 60000,
                'guide_price_high' => 70000,
                'auction_date' => '2026-03-11',
                'lot_number' => 8,
                'status' => 'upcoming',
            ],
            [
                'auction_house_id' => 12,
                'title' => 'Warehouse Conversion Opportunity - 3,000 sq ft',
                'address' => 'Unit B, Ilkeston Road, Nottingham',
                'postcode' => 'NG7 3GR',
                'region' => 'East Midlands',
                'property_type' => 'commercial',
                'lot_condition' => 'development',
                'bedrooms' => null,
                'guide_price_low' => 150000,
                'guide_price_high' => 185000,
                'auction_date' => '2026-03-11',
                'lot_number' => 22,
                'status' => 'upcoming',
            ],

            // --- Hollis & Morgan (house_id: 67) ---
            [
                'auction_house_id' => 67,
                'title' => 'Detached Period Property - Grade II Listed',
                'address' => '2 Royal York Crescent, Bristol',
                'postcode' => 'BS8 4JY',
                'region' => 'South West',
                'property_type' => 'residential',
                'lot_condition' => 'refurbishment',
                'bedrooms' => 5,
                'guide_price_low' => 450000,
                'guide_price_high' => 550000,
                'auction_date' => '2026-04-01',
                'lot_number' => 1,
                'status' => 'upcoming',
            ],

            // --- Maggs & Allen (house_id: 85) ---
            [
                'auction_house_id' => 85,
                'title' => 'Commercial Investment - Let to National Covenant',
                'address' => '88 Gloucester Road, Bristol',
                'postcode' => 'BS7 8BN',
                'region' => 'South West',
                'property_type' => 'commercial',
                'lot_condition' => 'modern',
                'bedrooms' => null,
                'guide_price_low' => 290000,
                'guide_price_high' => 340000,
                'auction_date' => '2026-04-01',
                'lot_number' => 16,
                'status' => 'upcoming',
            ],

            // --- John Pye (house_id: 73) ---
            [
                'auction_house_id' => 73,
                'title' => '1-Bed Flat - Liverpool Waterfront - Great Rental',
                'address' => 'Apartment 42, Princes Dock, Liverpool',
                'postcode' => 'L3 1BH',
                'region' => 'North West',
                'property_type' => 'residential',
                'lot_condition' => 'modern',
                'bedrooms' => 1,
                'guide_price_low' => 75000,
                'guide_price_high' => 90000,
                'auction_date' => '2026-03-13',
                'lot_number' => 10,
                'status' => 'upcoming',
            ],
            [
                'auction_house_id' => 73,
                'title' => '3-Bed Detached - Executor Sale - Derby',
                'address' => '18 Kedleston Road, Derby',
                'postcode' => 'DE22 1FT',
                'region' => 'East Midlands',
                'property_type' => 'residential',
                'lot_condition' => 'refurbishment',
                'bedrooms' => 3,
                'guide_price_low' => 140000,
                'guide_price_high' => 170000,
                'auction_date' => '2026-03-13',
                'lot_number' => 25,
                'status' => 'upcoming',
            ],

            // --- BidX1 (house_id: 17) ---
            [
                'auction_house_id' => 17,
                'title' => 'Studio Flat - Zone 2 London - 999yr Lease',
                'address' => 'Flat 6, 71 Camberwell Road',
                'postcode' => 'SE5 0EZ',
                'region' => 'London',
                'property_type' => 'residential',
                'lot_condition' => 'modern',
                'bedrooms' => 0,
                'guide_price_low' => 165000,
                'guide_price_high' => 195000,
                'auction_date' => '2026-03-21',
                'lot_number' => 4,
                'status' => 'upcoming',
            ],

            // --- Drivers & Norris (house_id: 43) ---
            [
                'auction_house_id' => 43,
                'title' => '2-Bed Garden Flat - Islington - Vacant',
                'address' => 'Ground Floor, 90 Holloway Road',
                'postcode' => 'N7 8JG',
                'region' => 'London',
                'property_type' => 'residential',
                'lot_condition' => 'refurbishment',
                'bedrooms' => 2,
                'guide_price_low' => 350000,
                'guide_price_high' => 400000,
                'auction_date' => '2026-04-09',
                'lot_number' => 3,
                'status' => 'upcoming',
            ],

            // --- Loveitts (house_id: 83) ---
            [
                'auction_house_id' => 83,
                'title' => '3-Bed Semi - Coventry - Lender Repossession',
                'address' => '52 Stoney Stanton Road, Coventry',
                'postcode' => 'CV1 4FP',
                'region' => 'West Midlands',
                'property_type' => 'residential',
                'lot_condition' => 'refurbishment',
                'bedrooms' => 3,
                'guide_price_low' => 75000,
                'guide_price_high' => 90000,
                'auction_date' => '2026-03-26',
                'lot_number' => 19,
                'status' => 'upcoming',
            ],

            // --- Fisher German (house_id: 51) ---
            [
                'auction_house_id' => 51,
                'title' => 'Agricultural Land - 12 Acres - Leicestershire',
                'address' => 'Land off Main Street, Market Harborough',
                'postcode' => 'LE16 7RT',
                'region' => 'East Midlands',
                'property_type' => 'land',
                'lot_condition' => 'mixed',
                'bedrooms' => null,
                'guide_price_low' => 120000,
                'guide_price_high' => 150000,
                'auction_date' => '2026-04-15',
                'lot_number' => 2,
                'status' => 'upcoming',
            ],

            // --- Cheffins (house_id: 32) ---
            [
                'auction_house_id' => 32,
                'title' => 'Barn Conversion Opportunity with PP',
                'address' => 'Manor Farm, Ely Road, Cambridge',
                'postcode' => 'CB5 8TH',
                'region' => 'East Anglia',
                'property_type' => 'residential',
                'lot_condition' => 'development',
                'bedrooms' => null,
                'guide_price_low' => 250000,
                'guide_price_high' => 300000,
                'auction_date' => '2026-03-28',
                'lot_number' => 7,
                'status' => 'upcoming',
            ],
            [
                'auction_house_id' => 32,
                'title' => '4-Bed Farmhouse - Substantial Renovation Project',
                'address' => 'The Old Rectory, Newmarket Road',
                'postcode' => 'CB8 7QL',
                'region' => 'East Anglia',
                'property_type' => 'residential',
                'lot_condition' => 'refurbishment',
                'bedrooms' => 4,
                'guide_price_low' => 375000,
                'guide_price_high' => 425000,
                'auction_date' => '2026-03-28',
                'lot_number' => 12,
                'status' => 'upcoming',
            ],

            // --- Online Property Auctions Scotland (house_id: 98) ---
            [
                'auction_house_id' => 98,
                'title' => '2-Bed Tenement Flat - Glasgow West End',
                'address' => '3/1, 42 Byres Road, Glasgow',
                'postcode' => 'G11 5JY',
                'region' => 'Scotland',
                'property_type' => 'residential',
                'lot_condition' => 'modern',
                'bedrooms' => 2,
                'guide_price_low' => 110000,
                'guide_price_high' => 130000,
                'auction_date' => '2026-03-15',
                'lot_number' => 5,
                'status' => 'upcoming',
            ],
            [
                'auction_house_id' => 98,
                'title' => '1-Bed Flat - Edinburgh New Town - Probate',
                'address' => '8/4 Dundas Street, Edinburgh',
                'postcode' => 'EH3 6HZ',
                'region' => 'Scotland',
                'property_type' => 'residential',
                'lot_condition' => 'refurbishment',
                'bedrooms' => 1,
                'guide_price_low' => 145000,
                'guide_price_high' => 175000,
                'auction_date' => '2026-04-12',
                'lot_number' => 8,
                'status' => 'upcoming',
            ],

            // --- Countrywide / Barnard Marcus (house_id: 39) ---
            [
                'auction_house_id' => 39,
                'title' => '2-Bed Flat - Lewisham - Great Transport Links',
                'address' => 'Flat 4, 159 Lewisham High Street',
                'postcode' => 'SE13 6AA',
                'region' => 'London',
                'property_type' => 'residential',
                'lot_condition' => 'modern',
                'bedrooms' => 2,
                'guide_price_low' => 200000,
                'guide_price_high' => 240000,
                'auction_date' => '2026-03-17',
                'lot_number' => 14,
                'status' => 'upcoming',
            ],
            [
                'auction_house_id' => 39,
                'title' => 'Garage Block - 6 Units - South London',
                'address' => 'Garages rear of Thornton Road, Croydon',
                'postcode' => 'CR0 3BY',
                'region' => 'London',
                'property_type' => 'commercial',
                'lot_condition' => 'mixed',
                'bedrooms' => null,
                'guide_price_low' => 85000,
                'guide_price_high' => 100000,
                'auction_date' => '2026-03-17',
                'lot_number' => 39,
                'status' => 'upcoming',
            ],

            // --- Dawsons (house_id: 41) ---
            [
                'auction_house_id' => 41,
                'title' => '3-Bed Semi - Swansea Valley - Needs TLC',
                'address' => '8 Neath Road, Pontardawe',
                'postcode' => 'SA8 4HG',
                'region' => 'Wales',
                'property_type' => 'residential',
                'lot_condition' => 'refurbishment',
                'bedrooms' => 3,
                'guide_price_low' => 65000,
                'guide_price_high' => 80000,
                'auction_date' => '2026-03-22',
                'lot_number' => 11,
                'status' => 'upcoming',
            ],

            // --- All Wales Auction (house_id: 4) ---
            [
                'auction_house_id' => 4,
                'title' => 'Cottage with Land - Rural Carmarthenshire',
                'address' => 'Bryn Cottage, Llandeilo Road',
                'postcode' => 'SA19 6RP',
                'region' => 'Wales',
                'property_type' => 'residential',
                'lot_condition' => 'refurbishment',
                'bedrooms' => 2,
                'guide_price_low' => 75000,
                'guide_price_high' => 95000,
                'auction_date' => '2026-04-05',
                'lot_number' => 3,
                'status' => 'upcoming',
            ],

            // --- Mark Jenkinson (house_id: 87) ---
            [
                'auction_house_id' => 87,
                'title' => '2-Bed Terrace - Sheffield - Near University',
                'address' => '28 Ecclesall Road, Sheffield',
                'postcode' => 'S11 8PY',
                'region' => 'Yorkshire',
                'property_type' => 'residential',
                'lot_condition' => 'modern',
                'bedrooms' => 2,
                'guide_price_low' => 95000,
                'guide_price_high' => 115000,
                'auction_date' => '2026-03-24',
                'lot_number' => 15,
                'status' => 'upcoming',
            ],
            [
                'auction_house_id' => 87,
                'title' => 'Industrial Unit - 2,500 sq ft - Rotherham',
                'address' => 'Unit 14, Parkgate Business Park',
                'postcode' => 'S62 6JQ',
                'region' => 'Yorkshire',
                'property_type' => 'commercial',
                'lot_condition' => 'modern',
                'bedrooms' => null,
                'guide_price_low' => 70000,
                'guide_price_high' => 85000,
                'auction_date' => '2026-03-24',
                'lot_number' => 31,
                'status' => 'upcoming',
            ],

            // --- Acuitus (house_id: 1) ---
            [
                'auction_house_id' => 1,
                'title' => 'Freehold Retail Investment - Let to Tesco Express',
                'address' => '245 High Road, Wood Green',
                'postcode' => 'N22 8HF',
                'region' => 'London',
                'property_type' => 'commercial',
                'lot_condition' => 'modern',
                'bedrooms' => null,
                'guide_price_low' => 650000,
                'guide_price_high' => 750000,
                'auction_date' => '2026-04-17',
                'lot_number' => 3,
                'status' => 'upcoming',
            ],
            [
                'auction_house_id' => 1,
                'title' => 'Multi-Let Office Building - Manchester City Centre',
                'address' => '80 Deansgate, Manchester',
                'postcode' => 'M3 2ER',
                'region' => 'North West',
                'property_type' => 'commercial',
                'lot_condition' => 'modern',
                'bedrooms' => null,
                'guide_price_low' => 890000,
                'guide_price_high' => 1050000,
                'auction_date' => '2026-04-17',
                'lot_number' => 8,
                'status' => 'upcoming',
            ],

            // --- Butters John Bee (house_id: 29) ---
            [
                'auction_house_id' => 29,
                'title' => '3-Bed Semi - Stoke-on-Trent - Lender Sale',
                'address' => '22 London Road, Stoke-on-Trent',
                'postcode' => 'ST4 7QP',
                'region' => 'West Midlands',
                'property_type' => 'residential',
                'lot_condition' => 'refurbishment',
                'bedrooms' => 3,
                'guide_price_low' => 50000,
                'guide_price_high' => 65000,
                'auction_date' => '2026-03-20',
                'lot_number' => 8,
                'status' => 'upcoming',
            ],

            // --- Carter Jonas (house_id: 30) ---
            [
                'auction_house_id' => 30,
                'title' => '5-Bed Country House - Suffolk - 2 Acre Grounds',
                'address' => 'The Grange, Bury St Edmunds',
                'postcode' => 'IP33 2QR',
                'region' => 'East Anglia',
                'property_type' => 'residential',
                'lot_condition' => 'refurbishment',
                'bedrooms' => 5,
                'guide_price_low' => 550000,
                'guide_price_high' => 650000,
                'auction_date' => '2026-04-10',
                'lot_number' => 1,
                'status' => 'upcoming',
            ],

            // --- Greenslade Taylor Hunt (house_id: 57) ---
            [
                'auction_house_id' => 57,
                'title' => '2-Bed Cottage - Taunton - Character Property',
                'address' => '4 Silver Street, Taunton',
                'postcode' => 'TA1 3DN',
                'region' => 'South West',
                'property_type' => 'residential',
                'lot_condition' => 'refurbishment',
                'bedrooms' => 2,
                'guide_price_low' => 155000,
                'guide_price_high' => 185000,
                'auction_date' => '2026-03-30',
                'lot_number' => 6,
                'status' => 'upcoming',
            ],

            // --- Lambert Smith Hampton (house_id: 78) ---
            [
                'auction_house_id' => 78,
                'title' => 'Multi-Let Industrial Estate - Leeds - 92% Occupied',
                'address' => 'Crossgates Industrial Park, Leeds',
                'postcode' => 'LS15 8QG',
                'region' => 'Yorkshire',
                'property_type' => 'commercial',
                'lot_condition' => 'modern',
                'bedrooms' => null,
                'guide_price_low' => 1100000,
                'guide_price_high' => 1350000,
                'auction_date' => '2026-04-22',
                'lot_number' => 4,
                'status' => 'upcoming',
            ],

            // --- Harman Healy (house_id: 61) ---
            [
                'auction_house_id' => 61,
                'title' => '1-Bed Flat - Ealing Broadway - Chain Free',
                'address' => 'Flat 2, 55 Haven Green, Ealing',
                'postcode' => 'W5 2NX',
                'region' => 'London',
                'property_type' => 'residential',
                'lot_condition' => 'modern',
                'bedrooms' => 1,
                'guide_price_low' => 210000,
                'guide_price_high' => 250000,
                'auction_date' => '2026-04-03',
                'lot_number' => 11,
                'status' => 'upcoming',
            ],

            // --- Bradleys (house_id: 23) ---
            [
                'auction_house_id' => 23,
                'title' => '2-Bed Terrace - Exeter - Close to High Street',
                'address' => '19 Cowick Street, Exeter',
                'postcode' => 'EX4 1AL',
                'region' => 'South West',
                'property_type' => 'residential',
                'lot_condition' => 'refurbishment',
                'bedrooms' => 2,
                'guide_price_low' => 135000,
                'guide_price_high' => 160000,
                'auction_date' => '2026-04-07',
                'lot_number' => 9,
                'status' => 'upcoming',
            ],

            // --- Kivells (house_id: 75) ---
            [
                'auction_house_id' => 75,
                'title' => 'Smallholding - 8 Acres - Devon',
                'address' => 'Meadow Farm, Okehampton',
                'postcode' => 'EX20 1RW',
                'region' => 'South West',
                'property_type' => 'land',
                'lot_condition' => 'mixed',
                'bedrooms' => null,
                'guide_price_low' => 185000,
                'guide_price_high' => 225000,
                'auction_date' => '2026-04-07',
                'lot_number' => 2,
                'status' => 'upcoming',
            ],

            // --- Dedman Gray (house_id: 42) ---
            [
                'auction_house_id' => 42,
                'title' => '3-Bed Detached - Southend-on-Sea - Vacant',
                'address' => '8 Thorpe Hall Avenue, Southend',
                'postcode' => 'SS1 3AT',
                'region' => 'South East',
                'property_type' => 'residential',
                'lot_condition' => 'refurbishment',
                'bedrooms' => 3,
                'guide_price_low' => 220000,
                'guide_price_high' => 260000,
                'auction_date' => '2026-03-27',
                'lot_number' => 4,
                'status' => 'upcoming',
            ],

            // --- Future Property Auctions (house_id: 53) ---
            [
                'auction_house_id' => 53,
                'title' => '2-Bed Flat - Leeds City Centre - New Build',
                'address' => 'Apt 201, Whitehall Place, Leeds',
                'postcode' => 'LS1 4HR',
                'region' => 'Yorkshire',
                'property_type' => 'residential',
                'lot_condition' => 'modern',
                'bedrooms' => 2,
                'guide_price_low' => 125000,
                'guide_price_high' => 145000,
                'auction_date' => '2026-03-29',
                'lot_number' => 7,
                'status' => 'upcoming',
            ],

            // --- Landwood Property (house_id: 79) ---
            [
                'auction_house_id' => 79,
                'title' => 'Former Care Home - Conversion Opportunity - 12 Beds',
                'address' => 'Hillcrest House, Bolton',
                'postcode' => 'BL1 4QN',
                'region' => 'North West',
                'property_type' => 'commercial',
                'lot_condition' => 'development',
                'bedrooms' => null,
                'guide_price_low' => 275000,
                'guide_price_high' => 350000,
                'auction_date' => '2026-04-14',
                'lot_number' => 2,
                'status' => 'upcoming',
            ],

            // --- Brown & Co (house_id: 27) ---
            [
                'auction_house_id' => 27,
                'title' => 'Grade II Listed Barn with PP for Residential',
                'address' => 'Home Farm, Holt, Norfolk',
                'postcode' => 'NR25 6SU',
                'region' => 'East Anglia',
                'property_type' => 'residential',
                'lot_condition' => 'development',
                'bedrooms' => null,
                'guide_price_low' => 200000,
                'guide_price_high' => 250000,
                'auction_date' => '2026-04-18',
                'lot_number' => 5,
                'status' => 'upcoming',
            ],

            // --- Hunters (house_id: 70) ---
            [
                'auction_house_id' => 70,
                'title' => '2-Bed Terrace - Bradford - High Yield Area',
                'address' => '17 Manningham Lane, Bradford',
                'postcode' => 'BD1 3EA',
                'region' => 'Yorkshire',
                'property_type' => 'residential',
                'lot_condition' => 'refurbishment',
                'bedrooms' => 2,
                'guide_price_low' => 35000,
                'guide_price_high' => 45000,
                'auction_date' => '2026-03-23',
                'lot_number' => 17,
                'status' => 'upcoming',
            ],

            // --- Andrew Craig (house_id: 6) ---
            [
                'auction_house_id' => 6,
                'title' => '3-Bed Flat - Gateshead - River Views',
                'address' => '6 Hillgate Quays, Gateshead',
                'postcode' => 'NE8 2FD',
                'region' => 'North East',
                'property_type' => 'residential',
                'lot_condition' => 'modern',
                'bedrooms' => 3,
                'guide_price_low' => 85000,
                'guide_price_high' => 100000,
                'auction_date' => '2026-04-20',
                'lot_number' => 10,
                'status' => 'upcoming',
            ],

            // --- McHugh & Co (house_id: 90) ---
            [
                'auction_house_id' => 90,
                'title' => '2-Bed Victorian Terrace - Forest Gate - E7',
                'address' => '34 Woodgrange Road, Forest Gate',
                'postcode' => 'E7 0QH',
                'region' => 'London',
                'property_type' => 'residential',
                'lot_condition' => 'refurbishment',
                'bedrooms' => 2,
                'guide_price_low' => 300000,
                'guide_price_high' => 350000,
                'auction_date' => '2026-04-11',
                'lot_number' => 5,
                'status' => 'upcoming',
            ],
        ];

        foreach ($lots as $lot) {
            Lot::create($lot);
        }
    }
}
